<?php
/**
 * @file
 * feature_bioportal_collectie_lijst.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function feature_bioportal_collectie_lijst_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance:
  // 'node-naturalis_featured_content-field_collectie_afbeelding'.
  $field_instances['node-naturalis_featured_content-field_collectie_afbeelding'] = array(
    'bundle' => 'naturalis_featured_content',
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'image',
        'settings' => array(
          'image_link' => '',
          'image_style' => '',
        ),
        'type' => 'image',
        'weight' => 3,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_collectie_afbeelding',
    'label' => 'Afbeelding',
    'required' => 0,
    'settings' => array(
      'alt_field' => 0,
      'default_image' => 8,
      'file_directory' => '',
      'file_extensions' => 'png gif jpg jpeg',
      'max_filesize' => '',
      'max_resolution' => '',
      'min_resolution' => '',
      'title_field' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'image',
      'settings' => array(
        'preview_image_style' => 'medium',
        'progress_indicator' => 'throbber',
      ),
      'type' => 'image_image',
      'weight' => 32,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Afbeelding');

  return $field_instances;
}
