<?php

/**
 * Implements hook_menu().
 */
function nda_update_menu() {
  $items = array();
  $items['nda_update/batch_fix'] = array(
    'title' => 'Batch fix',
    'page callback' => 'nda_update_batch_fix',
    'access arguments' => array('administer users'),
  );
  return $items;
}

/**
 * The batch callback.
 */
function nda_update_batch_fix() {
  $batch = array(
    'operations' => array(),
    'finished' => 'nda_update_batch_fix_finished',
    'title' => t('Batch fix'),
    'init_message' => t('Fix is starting...'),
    'progress_message' => t('Processed @current out of @total.'),
    'error_message' => t('Fix has encountered an error.')
  );

  $query = db_query("SELECT nid from {node} WHERE type = 'national_search_area'");
  $records = $query->fetchAll();
  foreach ($records as $record) {
    $batch['operations'][] = array('nda_update_batch_fix_process', array($record));
  }
  batch_set($batch);
  batch_process(''); // batch_process('user'); // The path to redirect to when done.
}

/**
 * The batch processor.
 */
function nda_update_batch_fix_process($record, &$context) {
  // Do heavy lifting here...
  // Display a progress message...
  $node = node_load($record->nid);

  $context['message'] = "Now processing $node->title ...";

  node_delete($record->nid);
}

/**
 * The batch finish handler.
 */
function nda_update_batch_fix_finished($success, $results, $operations) {
  if ($success) {
    drupal_set_message('Fix is complete!');
  }
  else {
    $error_operation = reset($operations);
    $message = t('An error occurred while processing %error_operation with arguments: @arguments', array(
      '%error_operation' => $error_operation[0],
      '@arguments' => print_r($error_operation[1], TRUE)
    ));
    drupal_set_message($message, 'error');
  }
  drupal_set_message(l('Run again', 'nda_update/batch_fix'));
}
