<?php
/**
 * @file
 * thematic_menu.features.uuid_node.inc
 */

/**
 * Implements hook_uuid_features_default_content().
 */
function thematic_menu_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
  'title' => 'The Siebold Collection',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'ds_switch' => '',
  'type' => 'naturalis_featured_content',
  'language' => 'en',
  'created' => 1418388271,
  'tnid' => 3409,
  'translate' => 0,
  'uuid' => '27488ec8-d9fc-499b-98eb-c216a74c6ff1',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>The Siebold Collection of natural history objects includes a total of 200 mammals, 900 birds, 750 fishes, 170 reptiles, over 5,000 invertebrates, 2,000 different species of plants and 12,000 herbarium specimens. Many of these are stored in Naturalis\' collection depots, part of which has been digitized and made available in the BioPortal. The material was collected by Von Siebold, between 1823 and 1829, during his stay in Japan. The Siebold Collection was the first major collection of Japanese specimen in Europe and contained many species of plants and animals that were unknown in Europe at the time. <a href="http://www.naturalis.nl/nl/kennis/collectie/siebold-de-collectie/" style="text-decoration:none;" target="_blank"><u>Read more</u></a> [Dutch]</p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_nba_search_term' => array(
    'und' => array(
      0 => array(
        'value' => 'siebold',
        'format' => NULL,
      ),
    ),
  ),
  'metatags' => array(),
  'date' => '2014-12-12 12:44:31 +0000',
  'user_uuid' => '3f7b751f-de9b-4b15-b939-437e11ff7ae7',
);
  $nodes[] = array(
  'title' => 'Arts Collection',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 1,
  'sticky' => 0,
  'ds_switch' => '',
  'type' => 'naturalis_featured_content',
  'language' => 'en',
  'created' => 1418387855,
  'tnid' => 3406,
  'translate' => 0,
  'uuid' => '38a198b7-d5bf-49e1-9f95-d68a2d8615f6',
  'body' => array(),
  'field_nba_search_term' => array(
    'und' => array(
      0 => array(
        'value' => 'arts',
        'format' => NULL,
      ),
    ),
  ),
  'metatags' => array(),
  'date' => '2014-12-12 12:37:35 +0000',
  'user_uuid' => '3f7b751f-de9b-4b15-b939-437e11ff7ae7',
);
  $nodes[] = array(
  'title' => 'Prentencollectie',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'ds_switch' => '',
  'type' => 'naturalis_featured_content',
  'language' => 'nl',
  'created' => 1418387934,
  'tnid' => 3406,
  'translate' => 0,
  'uuid' => '8e9b0428-45a4-46ce-8bd7-e2201c73d0bc',
  'body' => array(),
  'field_nba_search_term' => array(
    'und' => array(
      0 => array(
        'value' => 'arts',
        'format' => NULL,
      ),
    ),
  ),
  'metatags' => array(),
  'date' => '2014-12-12 12:38:54 +0000',
  'user_uuid' => '3f7b751f-de9b-4b15-b939-437e11ff7ae7',
);
  $nodes[] = array(
  'title' => 'Beekbergerwoud Collectie',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'ds_switch' => '',
  'type' => 'naturalis_featured_content',
  'language' => 'nl',
  'created' => 1418481411,
  'tnid' => 3408,
  'translate' => 0,
  'uuid' => '944d927e-dca4-4567-8d40-0f2e13b2a0c9',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Het Beekbergerwoud behoort met 160 vermelde en/of verzamelde plantensoorten uit de periode 1827-1875 tot de best doorvorste Nederlanse natuurgebieden uit de 19de eeuw. Wat nog niet volledig geïnventariseerd is zijn de zoölogische collecties uit het Beekbergerwoud gemaakt in dezelfde periode. Dat is een gemis omdat herintroductie van lokaal uitgestorven soorten zich tegenwoordig allang niet meer beperkt tot alleen plantensoorten. Het bijeenbrengen van deze gegevens zal toekomstige herintroducties van de vroegere fauna uit het Beekbergerwoud helpen faciliteren zodat herstel van de dierenwereld van dit bos geen eeuwen hoeft te duren.&nbsp;<a href="https://science.naturalis.nl/en/education/bachelor-students/projects/#Beekbergerwoud" style="line-height: 20.7999992370605px;" target="_blank">Lees meer</a></p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_nba_search_term' => array(
    'und' => array(
      0 => array(
        'value' => 'beekbergerwoud',
        'format' => NULL,
      ),
    ),
  ),
  'metatags' => array(),
  'date' => '2014-12-13 14:36:51 +0000',
  'user_uuid' => '3f7b751f-de9b-4b15-b939-437e11ff7ae7',
);
  $nodes[] = array(
  'title' => 'Beekbergerwoud Collection',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'ds_switch' => '',
  'type' => 'naturalis_featured_content',
  'language' => 'en',
  'created' => 1418388036,
  'tnid' => 3408,
  'translate' => 0,
  'uuid' => 'aa7323fe-cb8d-469b-99e3-99fb10de4a0a',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>With 160 registered and/or collected plant species from the period 1827-1875, the Beekbergerwoud is one of the most closely scrutinised 19th century Dutch nature conservation areas. The zoological collections from the Beekbergerwoud assembled during the same period have not yet been fully inventorised. This is a clear lacuna, as the reintroduction of locally-extinct species has for some time no longer been restricted to plant species alone.&nbsp;<br />
Bringing all this information together will help distinguish facts from fables in the myths that have arisen around the Beekbergerwoud, thereby assisting future reintroductions of its former biodiversity.&nbsp;<a href="https://science.naturalis.nl/en/education/bachelor-students/projects/#Beekbergerwoud" style="line-height: 20.7999992370605px;" target="_blank">Read more</a></p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_nba_search_term' => array(
    'und' => array(
      0 => array(
        'value' => 'beekbergerwoud',
        'format' => NULL,
      ),
    ),
  ),
  'metatags' => array(),
  'date' => '2014-12-12 12:40:36 +0000',
  'user_uuid' => '3f7b751f-de9b-4b15-b939-437e11ff7ae7',
);
  $nodes[] = array(
  'title' => 'Extinct Birds',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'ds_switch' => '',
  'type' => 'naturalis_featured_content',
  'language' => 'en',
  'created' => 1418388320,
  'tnid' => 3410,
  'translate' => 0,
  'uuid' => 'ae3e44ac-969a-46ab-839e-a09f9cb81792',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>The more than 200 extinct birds in the Naturalis collection are a collection-highlight which raises much interest among ornithologists. 135 extinct birds specimen are accessible through the BioPortal. Some specimens are unique. Naturalis is the only museum in the world to hold a Tahiti-Sandpiper <em>Prosobonia leucoptera</em> (Gmelin, 1789) and a specimen of Sharpe\'s Rail <em>Gallirallus sharpei</em> (Büttikofer, 1893). You can view the digitized extinct birds in the collection from all angles by rotating the 3d-images.</p>

<p>The nomenclature is based on The Howard &amp; Moore Complete Checklist of the Birds of the World Dickinson, E.C. (Editor) 3rd Edition, Princeton University Press, 2003.</p>

<div>&nbsp;</div>

<div>&nbsp;</div>',
        'summary' => '',
        'format' => 'full_html',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_nba_search_term' => array(
    'und' => array(
      0 => array(
        'value' => 'extinct-birds',
        'format' => NULL,
      ),
    ),
  ),
  'metatags' => array(),
  'date' => '2014-12-12 12:45:20 +0000',
  'user_uuid' => '3f7b751f-de9b-4b15-b939-437e11ff7ae7',
);
  $nodes[] = array(
  'title' => 'De Siebold Collectie',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'ds_switch' => '',
  'type' => 'naturalis_featured_content',
  'language' => 'nl',
  'created' => 1418404304,
  'tnid' => 3409,
  'translate' => 0,
  'uuid' => 'c1b250fb-f79b-403b-93a9-61bf7d7d7b34',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>De Siebold Collectie van natuurhistorische objecten omvat in totaal 200 zoogdieren, 900 vogels, 750 vissen, 170 reptielen, meer dan 5000 ongewervelde dieren, 2000 verschillende soorten planten en 12.000 herbariumexemplaren. Een groot deel hiervan bevindt zich in de opslagtoren van Naturalis, een deel hiervan is ook gedigitaliseerd en beschikbaar in het BioPortal. Von Siebold verzamelde het materiaal tussen 1823 en 1829 tijdens zijn verblijf in Japan. De collectie was de eerste grote verzameling van Japanse specimen in Europa en bevatte veel tot dan toe onbekende dier- en plantensoorten.&nbsp;<a href="http://www.naturalis.nl/nl/kennis/collectie/siebold-de-collectie/" style="line-height: 20.7999992370605px; text-decoration: none;" target="_blank">Lees meer</a></p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_nba_search_term' => array(
    'und' => array(
      0 => array(
        'value' => 'siebold',
        'format' => NULL,
      ),
    ),
  ),
  'metatags' => array(),
  'date' => '2014-12-12 17:11:44 +0000',
  'user_uuid' => '3f7b751f-de9b-4b15-b939-437e11ff7ae7',
);
  $nodes[] = array(
  'title' => 'Uitgestorven Vogels',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'ds_switch' => '',
  'type' => 'naturalis_featured_content',
  'language' => 'nl',
  'created' => 1418480964,
  'tnid' => 3410,
  'translate' => 0,
  'uuid' => 'dc75ec2d-53f8-4e64-809d-feb302cf1193',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>De meer dan 200 uitgestorven vogelsoorten in de Naturalis collectie zijn een collectie-hoogtepunt waar veel interesse voor is vanuit ornithologen. 135 van deze soorten zijn beschikbaar in het BioPortal. Sommige exemplaren zijn uniek. Zo is Naturalis het enige museum in de wereld dat een Tahitistrandloper <em>Prosobonia leucoptera</em> (Gmelin, 1789) en een exemplaar van de Büttikofer-ral <em>Gallirallus sharpei</em> (Büttikofer, 1893) in de collectie heeft. Je kan hier de gedigitaliseerde uitgestorven vogels van alle kanten bekijken middels draaiende 3d-beelden.</p>

<p>De nomenclatuur is gebaseerd op The Howard &amp; Moore Complete Checklist of the Birds of the World Dickinson, E.C. (Editor) 3rd Edition, Princeton University Press, 2003.</p>

<div>&nbsp;</div>',
        'summary' => '',
        'format' => 'full_html',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_nba_search_term' => array(
    'und' => array(
      0 => array(
        'value' => 'extinct-birds',
        'format' => NULL,
      ),
    ),
  ),
  'metatags' => array(),
  'date' => '2014-12-13 14:29:24 +0000',
  'user_uuid' => '3f7b751f-de9b-4b15-b939-437e11ff7ae7',
);
  return $nodes;
}
