<?php
/**
 * @file
 * bioportal_serrvice_menu_pages.features.uuid_node.inc
 */

/**
 * Implements hook_uuid_features_default_content().
 */
function bioportal_serrvice_menu_pages_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
  'title' => 'About',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'ds_switch' => '',
  'type' => 'naturalis_page',
  'language' => 'en',
  'created' => 1417189687,
  'tnid' => 4,
  'translate' => 0,
  'uuid' => '046583ea-ed92-4f82-9641-f2821bea952a',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>The Bioportal is a website that serves as the national access portal for all information relating to natural history, from basic data about museum objects right through to fully illustrated species descriptions. Via a single website, BioPortal grants access to all digitised details about the Naturalis collections, using the Netherlands Biodiversity API (NBA). More than 4 million Naturalis objects are already ‘searchable’ via the BioPortal and by July 2015, the complete collection of 37 million objects will have been placed within the BioPortal. This information will continue to be further extended with all the data linked together in the NBA so that we in the Netherlands will be able to use a single website that enables us to consult the full range of digital sources, with a guaranteed level of scientific quality.</p>

<p>Via the NBA, Bioportal can access the following data sources</p>

<ul>
	<li>
	<p>Brahms: botanic specimen data at Naturalis</p>
	</li>
	<li>
	<p>Naturalis Collection Registration System (CRS): zoological, paleontological, mineralogical and petrological specimen data from Naturalis</p>
	</li>
	<li>
	<p><a href="http://www.nederlandsesoorten.nl/" style="text-decoration: none;">Nederlands Soortenregister<u>:</u></a>&nbsp;list with descriptions of all Dutch species</p>
	</li>
	<li>
	<p><a href="http://www.catalogueoflife.org/" style="text-decoration: none;"><u>Catalogue of Life</u></a>: list of species occurring worldwide</p>
	</li>
</ul>

<p>The BioPortal reflects the strength of the NBA. It is effectively a ‘client’ of the NBA, an example application that delivers data from the NBA in an appealing manner, via a web portal. By means of this portal, anyone – from the interested amateur to the research scientist – can carry out full-text searches or simply graze through the data using specific fields and geographical locations.</p>

<p>Within the portal, special Naturalis collections will be spotlighted, and thanks to their own menu are easily scrollable.</p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_summary' => '',
      ),
    ),
  ),
  'metatags' => array(),
  'date' => '2014-11-28 15:48:07 +0000',
  'user_uuid' => '3f7b751f-de9b-4b15-b939-437e11ff7ae7',
);
  $nodes[] = array(
  'title' => 'Disclaimer',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'ds_switch' => '',
  'type' => 'naturalis_service_menu_page',
  'language' => 'nl',
  'created' => 1418387024,
  'tnid' => 1,
  'translate' => 0,
  'uuid' => '185c8ef3-a60e-47dc-868d-146b4dc31b6e',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p><strong>Aan het op bioportal.naturalis.nl juist weergeven van informatie is door de redactie van Naturalis Biodiversity Center uiterste zorg besteed.</strong></p>

<p>Naturalis Biodiversity Center aanvaardt echter geen enkele aansprakelijkheid voor schade als gevolg van het gebruik, op welke wijze dan ook, van de aangeboden informatie op deze internetsite.</p>

<h2>Rechten</h2>

<p>De redactie heeft alles in het werk gesteld om bij het gebruik van data, teksten en beelden op deze site geen belangen van derden te schenden. Een ieder die niettemin meent dat op deze site materiaal gebruikt is zonder dat daarover met hem of haar als mogelijke rechthebbende afspraken zijn gemaakt, verzoeken wij contact op te nemen met de redactie (bioportal@naturalis.nl).﻿</p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_summary' => '',
      ),
    ),
  ),
  'metatags' => array(),
  'date' => '2014-12-12 12:23:44 +0000',
  'user_uuid' => '3f7b751f-de9b-4b15-b939-437e11ff7ae7',
);
  $nodes[] = array(
  'title' => 'Disclaimer',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'ds_switch' => '',
  'type' => 'naturalis_service_menu_page',
  'language' => 'en',
  'created' => 1413896301,
  'tnid' => 1,
  'translate' => 0,
  'uuid' => '1dfa43fc-f62c-4d40-a016-4e4f40952954',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p><strong>Every effort has been taken to ensure the accuracy of the information on bioportal.naturalis.nl.</strong></p>

<p>However, Naturalis Biodiversity Center excludes all and any liability for damage resulting from the use, in whatever manner, of information supplied on this site.</p>

<h2>Intellectual Property Rights</h2>

<p>Every effort has been taken to protect the interests of third parties when using data, texts and pictures. If, however, you believe that this site contains material that is subject to intellectual property rights, without agreements having been reached with the rightful owner, please contact the web editors (bioportal@naturalis.nl).</p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_summary' => '',
      ),
    ),
  ),
  'metatags' => array(),
  'date' => '2014-10-21 12:58:21 +0000',
  'user_uuid' => '3f7b751f-de9b-4b15-b939-437e11ff7ae7',
);
  $nodes[] = array(
  'title' => 'Help',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'ds_switch' => '',
  'type' => 'naturalis_help',
  'language' => 'nl',
  'created' => 1413895042,
  'tnid' => 2,
  'translate' => 0,
  'uuid' => '3fbad984-3780-4e5e-b2a9-71488272d5b7',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Op deze site kan je zoeken op multimedia, specimen (collectie-exemplaren), taxa (o.a. soortbeschrijvingen) en op dieren, planten, paddenstoelen, fossielen, mineralen en stenen.</p>

<p>De informatie komt uit de catalogi van Naturalis Biodiversity Center te Leiden, uit het <a href="http://www.nederlandsesoorten.nl/" target="_blank"> Nederlands Soorten register</a>&nbsp;en uit de <a href="http://www.catalogueoflife.org/" target="_blank"> Catalogue of Life </a></p>

<p>Het BioPortal biedt vier mogelijkheden om deze gegevens te doorzoeken:</p>

<ul>
	<li><a href="#simple-search"><em>zoeken</em> </a></li>
	<li><a href="#advanced-search"><em>geavanceerd zoeken</em> </a></li>
	<li><a href="#geo-search"><em>geografisch zoeken</em> </a></li>
	<li><a href="#explore"><em>bijzondere collecties</em> </a></li>
</ul>

<p>&nbsp;<a name="simple-search"></a></p>

<h2>Zoeken</h2>

<p>&nbsp;</p>

<h3>Zoeken</h3>

<p>De zoekmachine in het Bioportal gebruikt jouw zoektermen om de verschillende&nbsp;bronnen te doorzoeken. Hij kijkt daarbij naar alle relevante&nbsp;velden, zoals de <em>populaire naam</em>,&nbsp;<em>wetenschappelijke naam</em>, vindplaats en registratienummer.</p>

<p><em>Voorbeeld</em> : je kan zowel op [ bruine rat ] als op [ rattus norvegicus ] zoeken.</p>

<p>Wanneer je een zoekopdracht uitvoert die uit meer dan één zoekterm bestaat, worden&nbsp;resultaten getoond waarin één, sommige of alle termen voorkomen.&nbsp;De resultaten worden zo weergegeven dat de best matchende bovenaan komt te staan.</p>

<p>Bij een simple search wordt een zoekterm geanalyseerd en dat leidt in het geval van meerdere termen tot een opdeling in brokjes. Dit zijn allemaal potentiele zoektermen die als een OR worden behandeld en dit kan zorgen voor een groot aantal zoekresultaten.</p>

<p><a name="advanced-search"></a><a name="multimedia"></a><a name="taxa"></a><a name="collection-specimens-by-name"></a><a name="collection-specimens"></a>Je kan geen gebruik maken van haakjes of zogenoemde <em> wildcards. </em>Om zoektermen te combineren kan je gebruik maken van de <a href="#advanced-search"> Advanced search </a></p>

<p>&nbsp;</p>

<h3>Geavanceerd zoeken</h3>

<p>Door op het driehoekje in het gewone zoekveld te klikken, worden de geavanceerde zoekopties zichtbaar. Hiermee kun&nbsp;je de resultaten beperken tot de categorieën&nbsp;(multimedia, specimen&nbsp;of taxa) en specifieke velden.</p>

<p>Binnen de rubrieken specimens en multimedia is het ook mogelijk te zoeken binnen een bepaalde collectie door de naam van een specifieke collectie te kiezen in het veld Collectienaam.</p>

<p>Wanneer je voor meer categorieën zoektermen opgeeft, worden voor elke categorie resultaten getoond.</p>

<p>Als je binnen een categorie meerdere zoekvelden invult, worden aanvankelijk slechts resultaten getoond die beide termen bevatten. Je <em>beperkt</em> hier het aantal resultaten mee.</p>

<p><a name="geo-search"></a>Wanneer je “Or” kiest voor “combine search terms” krijg je daarbij resultaten te zien die één van beide termen bevatten en breidt je de resultaten dus uit.</p>

<p>&nbsp;</p>

<h3>Geografisch zoeken</h3>

<p>Geografisch zoeken kan gebruikt worden om de zoekresultaten te beperken tot een bepaald gebied. Dit gebied kan gekozen worden uit de lijst gebieden rechts van de kaart of op de kaart getekend worden.&nbsp;Selecteer om zelf een gebied te tekenen het polygoon- of rechthoek-symbool midden bovenin de kaart, en klik vervolgens in de kaart om het gebied te tekenen. Wanneer je een polygoon tekent, kun je hem sluiten door dubbel te klikken.</p>

<p>Alleen resultaten waarvan de geografische coördinaten van de vindplaats opgenomen zijn in de bronsystemen, worden hier getoond.&nbsp;De resultaten zijn daarom altijd beperkt tot specimens en multimedia.</p>

<p><a name="explore"></a>We maken gebruik van verschillende <a href="/nl/colofon#sources?language=nl" target="_blank">bronnen</a>. Daardoor kan het voorkomen dat gebieden dubbel genoemd worden. Vaak verschillen deze gebieden in de gedetaileerdheid van de begrenzing.</p>

<p>&nbsp;</p>

<h3>Bijzondere collecties</h3>

<p>Een eenvoudige en snelle manier van zoeken is “Bijzondere collecties”. Hiermee zie je alle specimen die behoren tot een van de bijzondere collecties van Naturalis. Je krijgt direct alle resultaten te zien.</p>

<h2>Zoekresultaten</h2>

<p>Het&nbsp;BioPortal probeert je snel de resultaten te geven die je zoekt en gebruikt daarvoor <em>name resolution</em> en <em>ranking</em> .</p>

<h3>Name resolution</h3>

<p>Het BioPortal zal trachten jouw zoekterm te <em>matchen</em> met een wetenschappelijke naam. Dit wordt gedaan door verschillende velden te doorzoeken van het <a href="http://www.nederlandsesoorten.nl/" target="_blank">Nederlands Soorten Register</a> en de <a href="http://www.catalogueoflife.org/" target="_blank">Catalogue of Life</a></p>

<ol>
	<li>
	<p>Wetenschappelijke naam</p>

	<ul>
		<li>
		<p>Bijvoorbeeld: <em>“Rattus norvegicus”</em></p>
		</li>
	</ul>
	</li>
	<li>
	<p>Een lijst met populaire namen in verschillende talen</p>

	<ul>
		<li>
		<p>Bijvoorbeeld “Bruine Rat” (Nederlands) of “Brown Rat ” (Engels)</p>
		</li>
	</ul>
	</li>
	<li>
	<p>Hogere ordeningen</p>

	<ul>
		<li>
		<p>Bijvoorbeeld “Rodentia” voor de biologische orde van de knaagdieren</p>
		</li>
	</ul>
	</li>
</ol>

<p>&nbsp;</p>

<p>Deze wetenschappelijke naam wordt vervolgens gebruikt voor het doorzoeken van multimedia en specimens. Hierdoor kan het zijn dat je jouw oorspronkelijke zoekopdracht niet letterlijk terugziet in sommige resultaten.</p>

<h3>Ranking</h3>

<p>De zoekresultaten worden geordend aan de hand van</p>

<ol>
	<li>
	<p>Volledige <em>match</em> op de wetenschappelijke naam</p>
	</li>
	<li>
	<p>Volledige <em>match</em> op de soortnaam</p>
	</li>
	<li>
	<p>Volledige <em>match</em> op de naam van het geslacht</p>
	</li>
	<li>
	<p>Gedeeltelijke <em>match</em> op de wetenschappelijke naam</p>
	</li>
	<li>
	<p>Volledige <em>match</em> op enig ander veld</p>
	</li>
	<li>
	<p>Gedeeltelijke <em>match</em> op enig ander veld</p>
	</li>
	<li>
	<p>Gewicht van het zoekveld</p>
	</li>
</ol>

<h3>Categorieën</h3>

<p>De zoekresultaten zijn onderverdeeld in vier categorieën:</p>

<ol>
	<li>
	<p>Multimedia: afbeeldingen, geluid of bewegend beeld</p>
	</li>
	<li>
	<p>Taxa (soortbeschrijvingen)</p>
	</li>
	<li>
	<p>Specimen met de zoekterm in de soortnaam.&nbsp;Resultaten waarvan in de taxonomische informatie van het specimen de zoekterm voorkomt</p>
	</li>
	<li>
	<p>Specimens met de zoekterm in een ander veld.&nbsp;Resultaten waarbij de zoekterm voorkomt in bijvoorbeeld collectie-informatie, geografische informatie of informatie met betrekking tot datum en tijd. “Rat” geeft bijvoorbeeld ook resultaten die “Rat Island” als vindplaats hebben</p>
	</li>
</ol>

<p>Specimens zijn verwijzingen naar en beschrijvingen van objecten die zijn opgeslagen in de collectie van Naturalis (en soms ook daarbuiten). Deze beschrijvingen kunnen veel verschillende velden bevatten.</p>',
        'summary' => '',
        'format' => 'full_html',
        'safe_summary' => '',
      ),
    ),
  ),
  'metatags' => array(),
  'date' => '2014-10-21 12:37:22 +0000',
  'user_uuid' => '3f7b751f-de9b-4b15-b939-437e11ff7ae7',
);
  $nodes[] = array(
  'title' => 'API',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'ds_switch' => '',
  'type' => 'naturalis_page',
  'language' => 'en',
  'created' => 1417081488,
  'tnid' => 411615,
  'translate' => 0,
  'uuid' => '400c73b8-5ad3-44eb-a513-c019e8ef8fce',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<h2>The Netherlands Biodiversity API is a biodiversity data service</h2>

<p>The Netherlands Biodiversity API is a modern data service for scientists, application developers, national and regional government bodies and anyone else interested in biodiversity and biodiversity-related data. The provision of biodiversity-related data by the <a href="http://www.naturalis.nl/"  target="_blank">Naturalis Biodiversity Center</a>&nbsp;is the starting point for this service. By granting access to its very extensive catalogue, historical and recent data relating to a variety of species will be made available, including specimen, multimedia and taxon data.</p>

<h2>Netherlands Biodiversity API offers a raft of possibilities</h2>

<p>The information released via this application is eminently suitable for use by scientists working in taxonomical and thematic biodiversity studies. Detailed inventories of various types and a wide variety of (historical) data analyses are just some of the possible applications. For government bodies, the data can be an important source of information in developing new nature (conservation) policy as well as evaluating and monitoring existing policy in this field. Finally, application developers will be able to use the interface to bring plants, fungi, animals, fossils, minerals and rocks to life in interactive applications, aimed at specific target groups.</p>

<h2>Netherlands Biodiversity API starts by opening up the extensive Naturalis Collection</h2>

<p>The collection at Naturalis is one of the largest in the world. As well as their numbers, the quality of the objects is excellent, and together they are of immeasurable scientific value. Financed with FES (Economic Structure Enhancement) funds over the past few years, Naturalis has undertaken a unique digitisation project, according to which by 1 July 2015, all 37 million objects will have been recorded on digital cards, 7 million of them to a high level of detail. All in all, from the moment of its initial launch, this means that the Netherlands Biodiversity API is not only extensive in terms of size but also offers a valuable level of in-depth information.</p>

<h2>Netherlands Biodiversity API is freely accessible</h2>

<p>Naturalis has opted to place all its data in the public domain under&nbsp;<a href="https://creativecommons.org/choose/zero/"  target="_blank">CC0 licence</a>, making it free for all to use. In other words, users require no authorisation to gain access to the biodiversity data.</p>

<h2>Netherlands Biodiversity API and compatibility</h2>

<p>Naturalis aims to achieve compatibility with previous versions when carrying out maintenance on this API. Whenever it becomes necessary to add a function, as a consequence of which compatibility can no longer be guaranteed, the active version will continue to be maintained for a further 6 months, while the new function will only be available in the higher version. In the event of security problems or system abuse, Naturalis reserves the right to deviate from this principle.</p>

<h2>More about the Netherlands Biodiversity API</h2>

<p>Further information or questions about the Netherlands Biodiversity API</p>

<p><a href="http://docs.biodiversitydata.nl"  target="_blank">Github</a>&nbsp;offers more functional and technical information.</p>

<p>For questions, requests or comments, please mail to: <a href="mailto:nba@naturalis.nl">nba@naturalis.nl</a></p>

<p>&nbsp;</p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_summary' => '',
      ),
    ),
  ),
  'metatags' => array(),
  'date' => '2014-11-27 09:44:48 +0000',
  'user_uuid' => '3f7b751f-de9b-4b15-b939-437e11ff7ae7',
);
  $nodes[] = array(
  'title' => 'Colofon',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'ds_switch' => '',
  'type' => 'naturalis_service_menu_page',
  'language' => 'und',
  'created' => 1418386498,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '70fafe97-934d-4133-ab69-9147dccd7402',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<h2>Terms of use</h2>

<p>Unless otherwise stated, for the content on this site the Creative Commons Zero declaration (CC0) applies. This means that any form of reuse of the content of this site is permitted, except when for a piece of content (such as a photo or a document) copyright is indicated.</p>

<h2>Website design and construction</h2>

<p>Naturalis Biodiversity Center</p>

<h2>Data sources</h2>

<ul>
	<li>Naturalis Biodiversity Center (Botanical and Zoological specimen, species information)</li>
	<li>Species 2000 &amp; ITIS Catalogue of Life: 2014 Annual Checklist</li>
	<li>Natura 2000: ESRI-files from municipalities (Annemiek Adams)</li>
	<li>Staatsbosbeheer: ESRI-files from nature reserves (Jac Hakkens)</li>
	<li>Vereniging Natuurmonumenten: ESRI-files from nature reserves(Rombout de Wijs)</li>
</ul>

<h2>Data beschikbaarheid</h2>

<p>Naturalis onderschrijft de <a href="http://www.bouchoutdeclaration.org/">Bouchout Declaration</a>. De Bouchout Declaration streeft ernaar om digitale informatie over biodiversiteit publiek beschikbaar te maken. Hierdoor stimuleren en demonstreren we onze commitment aan vrij onderzoek.</p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_summary' => '',
      ),
    ),
  ),
  'metatags' => array(),
  'date' => '2014-12-12 12:14:58 +0000',
  'user_uuid' => '3f7b751f-de9b-4b15-b939-437e11ff7ae7',
);
  $nodes[] = array(
  'title' => 'Colophon',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'ds_switch' => '',
  'type' => 'naturalis_service_menu_page',
  'language' => 'en',
  'created' => 1413895260,
  'tnid' => 3,
  'translate' => 0,
  'uuid' => '794d5b17-da10-492e-839d-bbfce2ad70b4',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<h2>Terms of use</h2>

<p>Unless otherwise stated, for the content on this site the <a href="https://creativecommons.org/publicdomain/zero/1.0/"  target="_blank">Creative Commons Zero</a> declaration (CC0) applies. This means that any form of reuse of the content of this site is permitted, except when for a piece of content (such as a photo or a document) copyright is indicated.</p>

<p>Naturalis signed the <a href="http://www.bouchoutdeclaration.org/" target="_blank">Bouchout declaration</a> which aims to promote openness of biodiversity data and encourage digital access to those data.</p>

<h2>Website design and construction</h2>

<p>Naturalis Biodiversity Center</p>

<h2>Data sources</h2>

<ul>
	<li>Naturalis Biodiversity Center (Botanical and Zoological specimen, species information)</li>
	<li>Species 2000 &amp; ITIS Catalogue of Life: 2014 Annual Checklist</li>
	<li>Natura 2000: ESRI-files from municipalities (Annemiek Adams)</li>
	<li>Staatsbosbeheer: ESRI-files from nature reserves (Jac Hakkens)</li>
	<li>Vereniging Natuurmonumenten: ESRI-files from nature reserves(Rombout de Wijs)</li>
</ul>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_summary' => '',
      ),
    ),
  ),
  'metatags' => array(),
  'date' => '2014-10-21 12:41:00 +0000',
  'user_uuid' => '3f7b751f-de9b-4b15-b939-437e11ff7ae7',
);
  $nodes[] = array(
  'title' => 'Over',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'ds_switch' => '',
  'type' => 'naturalis_page',
  'language' => 'nl',
  'created' => 1418379970,
  'tnid' => 4,
  'translate' => 0,
  'uuid' => '7b5e25e8-c9cb-49c0-b450-5d403222a1cc',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Het BioPortal is de nationale toegangspoort voor natuurhistorische informatie: van basisgegevens van museumobjecten tot en met volledige, geïllustreerde soortbeschrijvingen. Via één website ontsluit het BioPortal alle gedigitaliseerde collectiegegevens van Naturalis met behulp van de Netherlands Biodiversity API (NBA). Nu zijn er al bijna 4 miljoen Naturalis objecten te doorzoeken, maar in juli 2015 is de complete collectie van 37 miljoen objecten via het BioPortal te vinden. De informatie wordt continu verder uitgebreid en middels de NBA gekoppeld en ontsloten, waarmee we in Nederland over een website beschikken waarin digitale bronnen van wetenschappelijk gegarandeerde kwaliteit samen zijn te raadplegen.</p>

<p>Het BioPortal bevraagt via de NBA de volgende databronnen:</p>

<ul>
	<li>Brahms: botanische specimengegevens van Naturalis.</li>
	<li>Collectie Registratie Systeem (CRS): zoölogische, palaeontologische, mineralogische en petrologische specimengegevens van Naturalis.</li>
	<li><a href="http://www.nederlandsesoorten.nl" target="_blank">Nederlands Soortenregister</a>: lijst en beschrijvingen van alle in Nederland voorkomende soorten.</li>
	<li><a href="http://www.catalogueoflife.org/" target="_blank">Catalogue of Life:</a><a href="http://www.catalogueoflife.org" target="_blank"> </a>lijst van wereldwijd voorkomende soorten.</li>
</ul>

<p>Het BioPortal toont de kracht van de NBA. Het is een “klant” van de NBA, een voorbeeldapplicatie die de gegevens uit de NBA via een webportaal toegankelijk maakt. Via dit portaal kan iedereen, geïnteresseerde of wetenschapper, in de gegevensbronnen van Naturalis grasduinen, met simpele zoekopdrachten, via complexe queries of op basis van specifieke geografische locaties.</p>

<p>Ook een aantal bijzondere collecties van Naturalis worden in het portaal uitgelicht, en zijn via het hoofdmenu direct te benaderen.</p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_summary' => '',
      ),
    ),
  ),
  'metatags' => array(),
  'date' => '2014-12-12 10:26:10 +0000',
  'user_uuid' => '3f7b751f-de9b-4b15-b939-437e11ff7ae7',
);
  $nodes[] = array(
  'title' => 'Colofon',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'ds_switch' => '',
  'type' => 'naturalis_service_menu_page',
  'language' => 'nl',
  'created' => 1418384571,
  'tnid' => 3,
  'translate' => 0,
  'uuid' => '7c8af603-88eb-418e-a735-6822dd7fe7f0',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<h2>Gebruiksvoorwaarden</h2>

<p>Tenzij anders aangegeven is op de gegevens op deze site de&nbsp;<a href="http://creativecommons.nl/uitleg/"  target="_blank">Creative Commons</a>&nbsp;Zero (CC0) verklaring van toepassing. Dit betekent dat iedere vorm van (her)gebruik van de inhoud is toegestaan, met uitzondering van content (zoals fotomateriaal of documenten) waarvan auteursrecht expliciet wordt vermeld.</p>

<p>Naturalis heeft de <a href="http://www.bouchoutdeclaration.org/" target="_blank">Bouchout Declaratie</a> ondertekend. Hiermee stimuleren en demonstreren we onze commitment aan vrij onderzoek. We streven er dan ook naar om digitale informatie over biodiversiteit publiek beschikbaar te maken via kanalen zoals dit portaal.</p>

<h2>Ontwerp en technische realisatie</h2>

<p>Naturalis Biodiversity Center</p>

<h2>Databronnen</h2>

<ul>
	<li>Naturalis Biodiversity Center (botanische en zoölogische specimen, soortinformatie)</li>
	<li>Species 2000 &amp; ITIS Catalogue of Life: Annual Checklist 2014</li>
	<li>Natura 2000: ESRI-bestanden van gemeenten (Annemiek Adams)</li>
	<li>Staatsbosbeheer: ESRI-bestanden van natuurgebieden (Jac Hakkens)</li>
	<li>Vereniging Natuurmonumenten: ESRI-bestanden van natuurgebieden (Rombout de Wijs)</li>
</ul>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_summary' => '',
      ),
    ),
  ),
  'metatags' => array(),
  'date' => '2014-12-12 11:42:51 +0000',
  'user_uuid' => '3f7b751f-de9b-4b15-b939-437e11ff7ae7',
);
  $nodes[] = array(
  'title' => 'Contact',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'ds_switch' => '',
  'type' => 'naturalis_service_menu_page',
  'language' => 'en',
  'created' => 1413984173,
  'tnid' => 6,
  'translate' => 0,
  'uuid' => 'a2f56bf1-1289-45f2-96a5-c25a057d6679',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<h2>Questions and feedback for BioPortal</h2>

<table border="0" style="width:100%">
	<tbody>
		<tr>
			<td style="width:50%">E-mail</td>
			<td><a href="mailto:bioportal@naturalis.nl">bioportal@naturalis.nl</a></td>
		</tr>
	</tbody>
</table>

<h2>Naturalis Biodiversity Center</h2>

<table border="0" style="width:100%">
	<tbody>
		<tr>
			<td style="width:50%">Visiting address</td>
			<td>Darwinweg 2, 2333 CR Leiden</td>
		</tr>
		<tr>
			<td>Postal address</td>
			<td>Postbus 9517, 2300 RA Leiden</td>
		</tr>
		<tr>
			<td>Telephone number</td>
			<td>+ 31-(0)71 568 7600</td>
		</tr>
		<tr>
			<td>Fax</td>
			<td>+ 31-(0)71 568 7666</td>
		</tr>
		<tr>
			<td>E-mail</td>
			<td><a href="mailto:contact@naturalis.nl" target="_blank">contact@naturalis.nl</a></td>
		</tr>
		<tr>
			<td>Office address</td>
			<td>Darwinweg 2, 2333 CR Leiden</td>
		</tr>
	</tbody>
</table>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_summary' => '',
      ),
    ),
  ),
  'metatags' => array(),
  'date' => '2014-10-22 13:22:53 +0000',
  'user_uuid' => '3f7b751f-de9b-4b15-b939-437e11ff7ae7',
);
  $nodes[] = array(
  'title' => 'API',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'ds_switch' => '',
  'type' => 'naturalis_page',
  'language' => 'nl',
  'created' => 1418379527,
  'tnid' => 411615,
  'translate' => 0,
  'uuid' => 'e96f0452-3460-4202-964f-9451ae5a7aa9',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<h2>Netherlands Biodiversity API is een biodiversiteitsdataservice</h2>

<p>De Netherlands Biodiversity API is een moderne dataservice voor wetenschappers, applicatieontwikkelaars, nationale en regionale overheidsinstanties, en andere geïnteresseerden in biodiversiteit en biodiversiteitsgegevens. Deze dienst start met het beschikbaar stellen van biodiversiteitsgegevens door het&nbsp;<a href="http://www.naturalis.nl" target="_blank">Naturalis Biodiversity Center</a>. &nbsp;Door haar zeer omvangrijke catalogi open te stellen komen diverse soorten historische en actuele data beschikbaar, namelijk specimen-, multimedia- en taxongegevens.</p>

<h2>Netherlands Biodiversity API biedt mogelijkheden</h2>

<p>De vrijgegeven gegevens zijn uitstekend geschikt voor gebruik door wetenschappers, werkzaam in het taxonomisch en thematisch biodiversiteitsonderzoek. Gedetailleerde inventarisaties van verschillende aard en een brede variëteit aan (historische) data-analyses behoren tot de gebruiksmogelijkheden. Voor overheden kunnen de gegevens een belangrijke bron van informatie vormen bij het ontwikkelen van nieuw natuur(bescherming)beleid, en, het evalueren en monitoren van staand beleid op dit terrein. Applicatieontwikkelaars tenslotte kunnen voor specifieke doelgroepen planten, paddenstoelen, dieren, fossielen, mineralen en gesteenten tot leven laten komen in interactieve applicaties.</p>

<h2>Netherlands Biodiversity API begint met het ontsluiten van de omvangrijke Naturalis Collectie</h2>

<p>De collectie van Naturalis behoort tot de grootste van de wereld. Behalve de hoeveelheid, is de kwaliteit van de objecten hoog en vertegenwoordigen ze een onschatbare wetenschappelijke waarde. Gefinancierd vanuit de FES gelden heeft Naturalis de afgelopen jaren een uniek digitaliseringsproject uitgevoerd, waarmee alle 37 miljoen objecten op 1 juli 2015 digitaal in kaart zijn gebracht, &nbsp;waarvan 7 miljoen objecten op een hoog detailniveau. Dit alles maakt dat de Netherlands Biodiversity API reeds bij de start een omvangrijk karakter heeft met een waardevolle mate van diepgang.</p>

<h2>Netherlands Biodiversity API is vrij toegankelijk</h2>

<p>Naturalis zet al haar data in het open domein onder&nbsp;<a href="http://creativecommons.nl/uitleg/" target="_blank">CC0-licentie</a>, dus vrij voor een ieder om te gebruiken. Een gebruiker heeft dus geen autorisatie nodig om toegang te krijgen tot de biodiversiteitsgegevens.</p>

<h2>Netherlands Biodiversity API en compatibiliteit</h2>

<p>Naturalis streeft naar compatibiliteit bij het onderhoud van deze API met eerdere versies. Wanneer het noodzakelijk is om functionaliteit toe te voegen waardoor deze compatibiliteit niet meer kan worden gegarandeerd, dan zal de actieve versie nog zes maanden onderhouden worden, en zal de nieuwe functionaliteit alleen in de hogere versie beschikbaar zijn. In het geval van veiligheidsproblemen of onjuist gebruik behoudt Naturalis zich het recht voor om hiervan af te wijken.</p>

<h2>Meer over Netherlands Biodiversity API</h2>

<p>Informatie of vragen over de Netherlands Biodiversity API</p>

<p>Op <a href="http://docs.biodiversitydata.nl/en/latest/" target="_blank">Github</a> vindt u meer functionele en technische informatie over de API.</p>

<p>Voor vragen, verzoeken en opmerkingen kunt u mailen met: <a href="mailto:nba@naturalis.nl">nba@naturalis.nl</a></p>

<p>&nbsp;</p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_summary' => '',
      ),
    ),
  ),
  'metatags' => array(),
  'date' => '2014-12-12 10:18:47 +0000',
  'user_uuid' => '3f7b751f-de9b-4b15-b939-437e11ff7ae7',
);
  return $nodes;
}
