<?php
/**
 * @file
 * bioportal_serrvice_menu_pages.features.uuid_node.inc
 */

/**
 * Implements hook_uuid_features_default_content().
 */
function bioportal_serrvice_menu_pages_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
  'title' => 'About',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'ds_switch' => '',
  'type' => 'naturalis_page',
  'language' => 'en',
  'created' => 1493645348,
  'tnid' => 3796,
  'translate' => 0,
  'uuid' => '046583ea-ed92-4f82-9641-f2821bea952a',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>The Bioportal is a website that serves as the national access portal for all information relating to natural history, from basic data about museum objects right through to fully illustrated species descriptions. Via a single website, BioPortal grants access to all digitised details about the Naturalis collections, using the Netherlands Biodiversity API (NBA). More than 4 million Naturalis objects are already ‘searchable’ via the BioPortal and by July 2015, the complete collection of 37 million objects will have been placed within the BioPortal. This information will continue to be further extended with all the data linked together in the NBA so that we in the Netherlands will be able to use a single website that enables us to consult the full range of digital sources, with a guaranteed level of scientific quality.</p>

<p>Via the NBA, Bioportal can access the following data sources</p>

<ul>
	<li>
	<p>Brahms: botanic specimen data at Naturalis</p>
	</li>
	<li>
	<p>Naturalis Collection Registration System (CRS): zoological, paleontological, mineralogical and petrological specimen data from Naturalis</p>
	</li>
	<li>
	<p><a href="http://www.nederlandsesoorten.nl/" style="text-decoration: none;">Nederlands Soortenregister<u>:</u></a>&nbsp;list with descriptions of all Dutch species</p>
	</li>
	<li>
	<p><a href="http://www.catalogueoflife.org/" style="text-decoration: none;"><u>Catalogue of Life</u></a>: list of species occurring worldwide</p>
	</li>
</ul>

<p>The BioPortal reflects the strength of the NBA. It is effectively a ‘client’ of the NBA, an example application that delivers data from the NBA in an appealing manner, via a web portal. By means of this portal, anyone – from the interested amateur to the research scientist – can carry out full-text searches or simply graze through the data using specific fields and geographical locations.</p>

<p>Within the portal, special Naturalis collections will be spotlighted, and thanks to their own menu are easily scrollable.</p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_file' => array(),
  'date' => '2017-05-01 13:29:08 +0000',
  'user_uuid' => '3f7b751f-de9b-4b15-b939-437e11ff7ae7',
);
  $nodes[] = array(
  'title' => 'Disclaimer',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'ds_switch' => '',
  'type' => 'naturalis_service_menu_page',
  'language' => 'nl',
  'created' => 1418387024,
  'tnid' => 1,
  'translate' => 0,
  'uuid' => '185c8ef3-a60e-47dc-868d-146b4dc31b6e',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<h2>Aan het op bioportal.naturalis.nl juist weergeven van informatie is door de redactie van Naturalis Biodiversity Center uiterste zorg besteed.</h2>

<p>Naturalis Biodiversity Center aanvaardt echter geen enkele aansprakelijkheid voor schade als gevolg van het gebruik, op welke wijze dan ook, van de aangeboden informatie op deze internetsite.</p>

<h2>Rechten</h2>

<p>De redactie heeft alles in het werk gesteld om bij het gebruik van data, teksten en beelden op deze site geen belangen van derden te schenden. Een ieder die niettemin meent dat op deze site materiaal gebruikt is zonder dat daarover met hem of haar als mogelijke rechthebbende afspraken zijn gemaakt, verzoeken wij contact op te nemen met de redactie (bioportal@naturalis.nl).﻿</p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_summary' => '',
      ),
    ),
  ),
  'date' => '2014-12-12 12:23:44 +0000',
  'user_uuid' => '3f7b751f-de9b-4b15-b939-437e11ff7ae7',
);
  $nodes[] = array(
  'title' => 'Disclaimer',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'ds_switch' => '',
  'type' => 'naturalis_service_menu_page',
  'language' => 'en',
  'created' => 1413896301,
  'tnid' => 1,
  'translate' => 0,
  'uuid' => '1dfa43fc-f62c-4d40-a016-4e4f40952954',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<h2>Every effort has been taken to ensure the accuracy of the information on bioportal.naturalis.nl.&nbsp;</h2>

<p>However, Naturalis Biodiversity Center excludes all and any liability for damage resulting from the use, in whatever manner, of information supplied on this site.</p>

<h2>Intellectual Property Rights</h2>

<p>Every effort has been taken to protect the interests of third parties when using data, texts and pictures. If, however, you believe that this site contains material that is subject to intellectual property rights, without agreements having been reached with the rightful owner, please contact the web editors (<a href="mailto:bioportal@naturalis.nl">bioportal@naturalis.nl</a>).</p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_summary' => '',
      ),
    ),
  ),
  'date' => '2014-10-21 12:58:21 +0000',
  'user_uuid' => '3f7b751f-de9b-4b15-b939-437e11ff7ae7',
);
  $nodes[] = array(
  'title' => 'Datasets',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'ds_switch' => '',
  'type' => 'naturalis_page',
  'language' => 'nl',
  'created' => 1500543934,
  'tnid' => 3790,
  'translate' => 0,
  'uuid' => '35464bbb-597f-4d33-97f5-be398cc7dec5',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>De volgende data sets zijn beschikbaar:</p>

<ul>
	<li><a href="sites/default/files/test.tar.gz">set 1</a></li>
	<li><a href="sites/default/files/test.tar">set 2</a></li>
	<li><a href="sites/default/files/test.zip">set 3</a></li>
</ul>

<p>&nbsp;</p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_file' => array(),
  'date' => '2017-07-20 09:45:34 +0000',
  'user_uuid' => '3f7b751f-de9b-4b15-b939-437e11ff7ae7',
);
  $nodes[] = array(
  'title' => 'Contact',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'ds_switch' => '',
  'type' => 'naturalis_service_menu_page',
  'language' => 'nl',
  'created' => 1418588269,
  'tnid' => 6,
  'translate' => 0,
  'uuid' => '3e237a01-bd06-477b-a693-da1c7686f9f1',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<h2>Vragen en suggesties over BioPortal</h2>

<table border="0" style="width:100%">
	<tbody>
		<tr>
			<td style="width:50%">E-mail</td>
			<td><a href="mailto:bioportal@naturalis.nl">bioportal@naturalis.nl</a></td>
		</tr>
	</tbody>
</table>

<h2>Naturalis Biodiversity Center</h2>

<table border="0" style="width:100%">
	<tbody>
		<tr>
			<td style="width:50%">Bezoekadres</td>
			<td>Darwinweg 2, 2333 CR Leiden</td>
		</tr>
		<tr>
			<td>Postadres</td>
			<td>Postbus 9517, 2300 RA Leiden</td>
		</tr>
		<tr>
			<td>Telefoonnummer</td>
			<td>+ 31-(0)71 568 7600</td>
		</tr>
		<tr>
			<td>Fax</td>
			<td>+ 31-(0)71 568 7666</td>
		</tr>
		<tr>
			<td>E-mail</td>
			<td><a href="mailto:contact@naturalis.nl">contact@naturalis.nl</a></td>
		</tr>
		<tr>
			<td>Kantoor</td>
			<td>Darwinweg 2, 2333 CR Leiden</td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td>&nbsp;</td>
		</tr>
	</tbody>
</table>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_summary' => '',
      ),
    ),
  ),
  'date' => '2014-12-14 20:17:49 +0000',
  'user_uuid' => '3f7b751f-de9b-4b15-b939-437e11ff7ae7',
);
  $nodes[] = array(
  'title' => 'Help',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'ds_switch' => '',
  'type' => 'naturalis_help',
  'language' => 'nl',
  'created' => 1413895042,
  'tnid' => 2,
  'translate' => 0,
  'uuid' => '3fbad984-3780-4e5e-b2a9-71488272d5b7',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Op deze site kun je zoeken op multimedia, specimens (collectie-exemplaren), taxa (dieren, planten, paddenstoelen), fossielen, mineralen en stenen.</p>

<p>De informatie komt uit de catalogi van <a href="http://www.naturalis.nl" style="text-decoration:none;" target="_blank">Naturalis Biodiversity Center</a> te Leiden, uit het <a href="http://www.nederlandsesoorten.nl/" style="text-decoration:none;" target="_blank">Nederlands Soortenregister</a> en uit de <a href="http://www.catalogueoflife.org/" style="text-decoration:none;" target="_blank">Catalogue of Life</a>.</p>

<p>Op de meeste specimenpagina’s is een PURL (Persistent Uniform Resource Locator) aanwezig. Als je dit object wilt citeren dan kun je gebruik maken van deze PURL. Naturalis stelt alles in het werk om het permanente karakter van deze PURL te garanderen.</p>

<p>Het BioPortal biedt vier mogelijkheden om deze gegevens te doorzoeken:</p>

<ul>
	<li><a href="#simple-search"><em>zoeken</em> </a></li>
	<li><a href="#advanced-search"><em>geavanceerd zoeken</em> </a></li>
	<li><a href="#geo-search"><em>geografisch zoeken</em> </a></li>
	<li><a href="#explore"><em>bijzondere collecties</em> </a></li>
</ul>

<p>&nbsp;<a name="simple-search"></a></p>

<h2>Zoeken</h2>

<p>&nbsp;</p>

<h3>Zoeken</h3>

<p>De zoekmachine in het BioPortal gebruikt jouw zoektermen om de verschillende bronnen te doorzoeken. Hij kijkt daarbij naar alle relevante velden, zoals de populaire naam, wetenschappelijke naam, vindplaats en registratienummer.</p>

<p>Voorbeeld : je kan zowel op [ bruine rat ] als op [ rattus norvegicus ] zoeken.</p>

<p>Wanneer je een zoekopdracht uitvoert die uit meer dan één zoekterm bestaat, worden resultaten getoond waarin één, sommige of alle termen voorkomen. De resultaten worden zo weergegeven dat de best matchende bovenaan komt te staan.</p>

<p>Bij een simple search wordt een zoekterm geanalyseerd en dat leidt in het geval van meerdere termen tot een opdeling in brokjes. Dit zijn allemaal potentiele zoektermen die als een OR worden behandeld en dit kan zorgen voor een groot aantal zoekresultaten.</p>

<p><a name="advanced-search"></a><a name="multimedia"></a><a name="taxa"></a><a name="collection-specimens-by-name"></a><a name="collection-specimens"></a>Je kan geen gebruik maken van haakjes of zogenoemde <em> wildcards. </em>Om zoektermen te combineren kan je gebruik maken van de <a href="#advanced-search"> Geavanceerd zoeken</a></p>

<p>&nbsp;</p>

<h3>Geavanceerd zoeken</h3>

<p>Door op het driehoekje in het gewone zoekveld te klikken, worden de geavanceerde zoekopties zichtbaar. Hiermee kun je de resultaten beperken tot de categorieën (multimedia, specimens of taxa) en specifieke velden.</p>

<p>Wanneer je voor meer categorieën zoektermen opgeeft, worden voor elke categorie resultaten getoond.</p>

<p>Als je binnen een categorie meerdere zoekvelden invult, worden resultaten getoond die één of meer van de ingevulde termen bevatten.</p>

<p>Wanneer je “En” kiest voor “Combineer zoektermen” krijg je resultaten te zien die alle ingevulde termen bevatten en beperk je de resultaten.</p>

<p>Binnen de categorieën Collectie specimens en Multimedia is het ook mogelijk te zoeken binnen een specifieke collectie door de naam van een collectie te kiezen in het veld Collectienaam. Eveneens&nbsp;<a name="geo-search"></a>kan de zoekopdracht&nbsp;voor de categorieën Collectie&nbsp;specimens, Taxa en Multimedia beperkt worden tot een bronsysteem (b.v. Botany of Zoology and Geology catalogues).</p>

<p>&nbsp;</p>

<h3>Geografisch zoeken</h3>

<p>Geografisch zoeken kan gebruikt worden om de zoekresultaten te beperken tot een bepaald gebied. Dit gebied kan gekozen worden uit de lijst gebieden rechts van de kaart of op de kaart getekend worden. Selecteer om zelf een gebied te tekenen het polygoon- of rechthoek-symbool midden bovenin de kaart, en klik vervolgens in de kaart om het gebied te tekenen.</p>

<p>Alleen resultaten waarvan de geografische coördinaten van de vindplaats opgenomen zijn in de bronsystemen worden hier getoond. De resultaten zijn daarom altijd beperkt tot specimens en multimedia.</p>

<p><a name="explore"></a>We maken gebruik van verschillende <a href="http://bioportal.naturalis.nl/nl/colofon#sources?language=nl" target="_blank">bronnen</a>. Daardoor kan het voorkomen dat gebieden dubbel genoemd worden. Vaak verschillen deze gebieden in de gedetaileerdheid van de begrenzing.</p>

<p>&nbsp;</p>

<h3>Bijzondere collecties</h3>

<p>Een eenvoudige en snelle manier van zoeken is “Bijzondere collecties”. Hiermee zie je alle specimens die behoren tot een van de bijzondere collecties van Naturalis. Je krijgt direct alle resultaten te zien.</p>

<h2>Zoekresultaten</h2>

<p>Het&nbsp;BioPortal probeert je snel de resultaten te geven die je zoekt en gebruikt daarvoor <em>name resolution</em> en <em>ranking</em>.</p>

<h3>Name resolution</h3>

<p>Het BioPortal zal trachten jouw zoekterm te <em>matchen</em> met een wetenschappelijke naam. Dit wordt gedaan door verschillende velden te doorzoeken van het <a href="http://www.nederlandsesoorten.nl/" target="_blank">Nederlands Soortenregister</a> en de <a href="http://www.catalogueoflife.org/" target="_blank">Catalogue of Life</a>.</p>

<ol>
	<li>
	<p>Wetenschappelijke naam</p>

	<ul>
		<li>
		<p>Bijvoorbeeld: <em>“Rattus norvegicus”</em></p>
		</li>
	</ul>
	</li>
	<li>
	<p>Een lijst met populaire namen in verschillende talen</p>

	<ul>
		<li>
		<p>Bijvoorbeeld “Bruine Rat” (Nederlands) of “Brown Rat ” (Engels)</p>
		</li>
	</ul>
	</li>
	<li>
	<p>Hogere ordeningen</p>

	<ul>
		<li>
		<p>Bijvoorbeeld “Rodentia” voor de biologische orde van de knaagdieren</p>
		</li>
	</ul>
	</li>
</ol>

<p><br />
Deze wetenschappelijke naam wordt vervolgens gebruikt voor het doorzoeken van multimedia en specimens. Hierdoor kan het zijn dat je jouw oorspronkelijke zoekopdracht niet letterlijk terugziet in sommige resultaten.</p>

<h3>Ranking</h3>

<p>De zoekresultaten worden geordend aan de hand van</p>

<ol>
	<li>
	<p>Volledige <em>match</em> op de wetenschappelijke naam</p>
	</li>
	<li>
	<p>Volledige <em>match</em> op de soortnaam</p>
	</li>
	<li>
	<p>Volledige <em>match</em> op de naam van het geslacht</p>
	</li>
	<li>
	<p>Gedeeltelijke <em>match</em> op de wetenschappelijke naam</p>
	</li>
	<li>
	<p>Volledige <em>match</em> op enig ander veld</p>
	</li>
	<li>
	<p>Gedeeltelijke <em>match</em> op enig ander veld</p>
	</li>
	<li>
	<p>Gewicht van het zoekveld</p>
	</li>
</ol>

<h3>Categorieën</h3>

<p>De zoekresultaten zijn onderverdeeld in vier categorieën:</p>

<ol>
	<li>
	<p>Multimedia: afbeeldingen, geluid of bewegend beeld</p>
	</li>
	<li>
	<p>Taxa (soortbeschrijvingen)</p>
	</li>
	<li>
	<p>Specimens met de zoekterm in de soortnaam.&nbsp;Resultaten waarvan in de taxonomische informatie van het specimen de zoekterm voorkomt</p>
	</li>
	<li>
	<p>Specimens met de zoekterm in een ander veld.&nbsp;Resultaten waarbij de zoekterm voorkomt in bijvoorbeeld collectie-informatie, geografische informatie of informatie met betrekking tot datum en tijd. “Rat” geeft bijvoorbeeld ook resultaten die “Rat Island” als vindplaats hebben</p>
	</li>
</ol>

<p>Specimens zijn verwijzingen naar en beschrijvingen van objecten die zijn opgeslagen in de collectie van Naturalis (en soms ook daarbuiten). Deze beschrijvingen kunnen veel verschillende velden bevatten.</p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_summary' => '',
      ),
    ),
  ),
  'path' => array(
    'pathauto' => 0,
  ),
  'pathauto_perform_alias' => FALSE,
  'date' => '2014-10-21 12:37:22 +0000',
  'user_uuid' => '3f7b751f-de9b-4b15-b939-437e11ff7ae7',
);
  $nodes[] = array(
  'title' => 'API',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'ds_switch' => '',
  'type' => 'naturalis_page',
  'language' => 'en',
  'created' => 1493645561,
  'tnid' => 411615,
  'translate' => 0,
  'uuid' => '400c73b8-5ad3-44eb-a513-c019e8ef8fce',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<h2>The Netherlands Biodiversity API is a biodiversity data service</h2>

<p>The Netherlands Biodiversity API is a modern data service for scientists, application developers, national and regional government bodies and anyone else interested in biodiversity and biodiversity-related data. The provision of biodiversity-related data by the <a href="http://www.naturalis.nl/en/" target="_blank">Naturalis Biodiversity Center</a>&nbsp;is the starting point for this service. By granting access to its very extensive catalogue, historical and recent data relating to a variety of species will be made available, including specimen, multimedia and taxon data.</p>

<h2>Netherlands Biodiversity API offers a raft of possibilities</h2>

<p>The information released via this application is eminently suitable for use by scientists working in taxonomical and thematic biodiversity studies. Detailed inventories of various types and a wide variety of (historical) data analyses are just some of the possible applications. For government bodies, the data can be an important source of information in developing new nature (conservation) policy as well as evaluating and monitoring existing policy in this field. Finally, application developers will be able to use the interface to bring plants, fungi, animals, fossils, minerals and rocks to life in interactive applications, aimed at specific target groups.</p>

<h2>Netherlands Biodiversity API starts by opening up the extensive Naturalis Collection</h2>

<p>The collection at Naturalis is one of the largest in the world. As well as their numbers, the quality of the objects is excellent, and together they are of immeasurable scientific value. Financed with FES (Economic Structure Enhancement) funds over the past few years, Naturalis has undertaken a unique digitisation project, according to which by 1 July 2015, all 37 million objects will have been recorded on digital cards, 7 million of them to a high level of detail. All in all, from the moment of its initial launch, this means that the Netherlands Biodiversity API is not only extensive in terms of size but also offers a valuable level of in-depth information.</p>

<h2>Netherlands Biodiversity API is freely accessible</h2>

<p>Unless stated otherwise, Naturalis has opted to place all its data in the public domain under&nbsp;<a href="https://creativecommons.org/choose/zero/" target="_blank">CC0 licence</a>, making it free for all to use. Users do not require authorisation to gain access to the biodiversity data. This means that any form of reuse of the content of this site is permitted, except when for a piece of content (such as a photo or a document) copyright is indicated.</p>

<h2>Netherlands Biodiversity API and compatibility</h2>

<p>Naturalis aims to achieve compatibility with previous versions when carrying out maintenance on this API. Whenever it becomes necessary to add a function, as a consequence of which compatibility can no longer be guaranteed, the active version will continue to be maintained for a further six months, while the new function will only be available in the higher version. In the event of security problems or system abuse, Naturalis reserves the right to deviate from this principle.</p>

<h2>More about the Netherlands Biodiversity API</h2>

<p>Further information or questions about the Netherlands Biodiversity API</p>

<p><a href="http://docs.biodiversitydata.nl" target="_blank">Github</a>&nbsp;offers more functional and technical information.</p>

<p>For questions, requests or comments, please mail to: <a href="mailto:nba@naturalis.nl">nba@naturalis.nl</a></p>

<p>&nbsp;</p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_file' => array(),
  'date' => '2017-05-01 13:32:41 +0000',
  'user_uuid' => '3f7b751f-de9b-4b15-b939-437e11ff7ae7',
);
  $nodes[] = array(
  'title' => 'Data sets',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'ds_switch' => '',
  'type' => 'naturalis_page',
  'language' => 'en',
  'created' => 1500543934,
  'tnid' => 3790,
  'translate' => 0,
  'uuid' => '40aaf623-f183-4bc3-a362-5dedaf994571',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Available data sets are:</p>

<ul>
	<li><a href="sites/default/files/test.tar.gz">set 1</a></li>
	<li><a href="sites/default/files/test.tar">set 2</a></li>
	<li><a href="sites/default/files/test.zip">set 3</a></li>
</ul>

<p>&nbsp;</p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_file' => array(),
  'date' => '2017-07-20 09:45:34 +0000',
  'user_uuid' => '3f7b751f-de9b-4b15-b939-437e11ff7ae7',
);
  $nodes[] = array(
  'title' => 'Disclaimer',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'ds_switch' => '',
  'type' => 'naturalis_service_menu_page',
  'language' => 'nl',
  'created' => 1418387013,
  'tnid' => 1,
  'translate' => 0,
  'uuid' => '4514bac5-0a1e-4989-ad4a-97a99e38a28c',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p><strong>Aan het op bioportal.naturalis.nl juist weergeven van informatie is door de redactie van Naturalis Biodiversity Center uiterste zorg besteed.</strong></p>

<p>Naturalis Biodiversity Center aanvaardt echter geen enkele aansprakelijkheid voor schade als gevolg van het gebruik, op welke wijze dan ook, van de aangeboden informatie op deze internetsite.</p>

<h2>Rechten</h2>

<p>De redactie heeft alles in het werk gesteld om bij het gebruik van data, teksten en beelden op deze site geen belangen van derden te schenden. Een ieder die niettemin meent dat op deze site materiaal gebruikt is zonder dat daarover met hem of haar als mogelijke rechthebbende afspraken zijn gemaakt, verzoeken wij contact op te nemen met de redactie (bioportal@naturalis.nl).﻿</p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_summary' => '',
      ),
    ),
  ),
  'date' => '2014-12-12 12:23:33 +0000',
  'user_uuid' => '3f7b751f-de9b-4b15-b939-437e11ff7ae7',
);
  $nodes[] = array(
  'title' => 'Colofon',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'ds_switch' => '',
  'type' => 'naturalis_service_menu_page',
  'language' => 'und',
  'created' => 1418386498,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '70fafe97-934d-4133-ab69-9147dccd7402',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<h2>Terms of use</h2>

<p>Unless otherwise stated, for the content on this site the Creative Commons Zero declaration (CC0) applies. This means that any form of reuse of the content of this site is permitted, except when for a piece of content (such as a photo or a document) copyright is indicated.</p>

<h2>Website design and construction</h2>

<p>Naturalis Biodiversity Center</p>

<h2>Data sources</h2>

<ul>
	<li>Naturalis Biodiversity Center (Botanical and Zoological specimen, species information)</li>
	<li>Species 2000 &amp; ITIS Catalogue of Life: 2014 Annual Checklist</li>
	<li>Natura 2000: ESRI-files from municipalities (Annemiek Adams)</li>
	<li>Staatsbosbeheer: ESRI-files from nature reserves (Jac Hakkens)</li>
	<li>Vereniging Natuurmonumenten: ESRI-files from nature reserves(Rombout de Wijs)</li>
</ul>

<h2>Data beschikbaarheid</h2>

<p>Naturalis onderschrijft de <a href="http://www.bouchoutdeclaration.org/">Bouchout Declaration</a>. De Bouchout Declaration streeft ernaar om digitale informatie over biodiversiteit publiek beschikbaar te maken. Hierdoor stimuleren en demonstreren we onze commitment aan vrij onderzoek.</p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_summary' => '',
      ),
    ),
  ),
  'date' => '2014-12-12 12:14:58 +0000',
  'user_uuid' => '3f7b751f-de9b-4b15-b939-437e11ff7ae7',
);
  $nodes[] = array(
  'title' => 'Colophon',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'ds_switch' => '',
  'type' => 'naturalis_service_menu_page',
  'language' => 'en',
  'created' => 1493645561,
  'tnid' => 3791,
  'translate' => 0,
  'uuid' => '794d5b17-da10-492e-839d-bbfce2ad70b4',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<h2>Terms of use</h2>

<p>Unless otherwise stated, for the content on this site the <a href="https://creativecommons.org/choose/zero/" style="text-decoration:none;" target="_blank">CC0 licence</a> applies. This means that any form of reuse of the content of this site is permitted, except when for a piece of content (such as a photo or a document) copyright is indicated.</p>

<p>Naturalis signed the <a href="http://bouchoutdeclaration.org/" style="text-decoration:none;" target="_blank">Bouchout declaration</a> which aims to promote openness of biodiversity data and encourage digital access to those data.</p>

<h2>Website design and construction</h2>

<p>Naturalis Biodiversity Center</p>

<h2>Data sources</h2>

<ul>
	<li><a href="http://www.naturalis.nl/en/" style="text-decoration:none;" target="_blank">Naturalis Biodiversity Center</a>: botanical and zoological specimens, species information</li>
	<li><a href="http://www.catalogueoflife.org" style="text-decoration:none;" target="_blank">Species 2000 &amp; ITIS Catalogue of Life</a>: Annual Checklist 2015</li>
	<li><a href="http://www.natura2000.nl" style="text-decoration:none;" target="_blank">Natura 2000</a>: ESRI-files of nature reserves (Annemiek Adams)</li>
	<li><a href="http://www.staatsbosbeheer.nl" style="text-decoration:none;" target="_blank">Staatsbosbeheer</a>: ESRI-files of nature reserves (Jac Hakkens)</li>
	<li><a href="https://www.natuurmonumenten.nl" style="text-decoration:none;" target="_blank">Vereniging Natuurmonumenten</a>: ESRI-files of nature reserves (Rombout de Wijs)</li>
	<li><a href="http://www.pwn.nl" style="text-decoration:none;" target="_blank">PWN</a>: ESRI-files of nature reserves (Hubert Kivit)</li>
	<li><a href="http://www.landschapnoordholland.nl" style="text-decoration:none;" target="_blank">Landschap Noord-Holland</a>: ESRI-files of nature reserves (Ron van \'t Veer)</li>
	<li><a href="http://www.cbs.nl/nl-NL/menu/home/default.htm" target="_blank">CBS Statistics Netherlands</a>: ESRI-bestanden of municipalities</li>
	<li><a href="http://gadm.org/" target="_blank">Global Administrative Areas</a>: ESRI-bestanden of administrative areas</li>
</ul>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_summary' => '',
      ),
    ),
  ),
  'date' => '2017-05-01 13:32:41 +0000',
  'user_uuid' => '3f7b751f-de9b-4b15-b939-437e11ff7ae7',
);
  $nodes[] = array(
  'title' => 'Over',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'ds_switch' => '',
  'type' => 'naturalis_page',
  'language' => 'nl',
  'created' => 1493645348,
  'tnid' => 3796,
  'translate' => 0,
  'uuid' => '7b5e25e8-c9cb-49c0-b450-5d403222a1cc',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Het BioPortal is de nationale toegangspoort voor natuurhistorische informatie: van basisgegevens van museumobjecten tot en met volledige, geïllustreerde soortbeschrijvingen. Via één website ontsluit het BioPortal alle gedigitaliseerde collectiegegevens van Naturalis met behulp van de Netherlands Biodiversity API (NBA). Nu zijn er al bijna 4 miljoen Naturalis objecten te doorzoeken, maar in juli 2015 is de complete collectie van 37 miljoen objecten via het BioPortal te vinden. De informatie wordt continu verder uitgebreid en middels de NBA gekoppeld en ontsloten, waarmee we in Nederland over een website beschikken waarin digitale bronnen van wetenschappelijk gegarandeerde kwaliteit samen zijn te raadplegen.</p>

<p>Het BioPortal bevraagt via de NBA de volgende databronnen:</p>

<ul>
	<li>Brahms: botanische specimengegevens van Naturalis.</li>
	<li>Collectie Registratie Systeem (CRS): zoölogische, palaeontologische, mineralogische en petrologische specimengegevens van Naturalis.</li>
	<li><a href="http://www.nederlandsesoorten.nl" target="_blank">Nederlands Soortenregister</a>: lijst en beschrijvingen van alle in Nederland voorkomende soorten.</li>
	<li><a href="http://www.catalogueoflife.org/" target="_blank">Catalogue of Life:</a><a href="http://www.catalogueoflife.org" target="_blank"> </a>lijst van wereldwijd voorkomende soorten.</li>
</ul>

<p>Het BioPortal toont de kracht van de NBA. Het is een “klant” van de NBA, een voorbeeldapplicatie die de gegevens uit de NBA via een webportaal toegankelijk maakt. Via dit portaal kan iedereen, geïnteresseerde of wetenschapper, in de gegevensbronnen van Naturalis grasduinen, met simpele zoekopdrachten, via complexe queries of op basis van specifieke geografische locaties.</p>

<p>Ook een aantal bijzondere collecties van Naturalis worden in het portaal uitgelicht, en zijn via het hoofdmenu direct te benaderen.</p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_file' => array(),
  'date' => '2017-05-01 13:29:08 +0000',
  'user_uuid' => '3f7b751f-de9b-4b15-b939-437e11ff7ae7',
);
  $nodes[] = array(
  'title' => 'Colofon',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'ds_switch' => '',
  'type' => 'naturalis_service_menu_page',
  'language' => 'nl',
  'created' => 1493645561,
  'tnid' => 3791,
  'translate' => 0,
  'uuid' => '7c8af603-88eb-418e-a735-6822dd7fe7f0',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<h2>Gebruiksvoorwaarden</h2>

<p>Tenzij anders aangegeven is op de gegevens op deze site de <a href="http://creativecommons.nl/publiek-domein/" style="text-decoration:none;" target="_blank">CC0 verklaring</a> van toepassing. Dit betekent dat iedere vorm van (her)gebruik van de inhoud is toegestaan, met uitzondering van content (zoals fotomateriaal of documenten) waarvan auteursrecht expliciet wordt vermeld.</p>

<p>Naturalis heeft de <a href="http://bouchoutdeclaration.org/" style="text-decoration:none;" target="_blank">Bouchout Declaratie</a> ondertekend. Hiermee stimuleren en demonstreren we onze commitment aan vrij onderzoek. We streven er dan ook naar om digitale informatie over biodiversiteit publiek beschikbaar te maken via kanalen zoals dit portaal.</p>

<h2>Ontwerp en technische realisatie</h2>

<p>Naturalis Biodiversity Center</p>

<h2>Databronnen</h2>

<ul>
	<li><a href="http://www.naturalis.nl" style="text-decoration:none;" target="_blank">Naturalis Biodiversity Center</a>: botanische en zoölogische specimens, soortinformatie</li>
	<li><a href="http://www.catalogueoflife.org" style="text-decoration:none;" target="_blank">Species 2000 &amp; ITIS Catalogue of Life</a>: Annual Checklist 2016</li>
	<li><a href="http://www.natura2000.nl" style="text-decoration:none;" target="_blank">Natura 2000</a>: ESRI-bestanden van natuurgebieden (Annemiek Adams)</li>
	<li><a href="http://www.staatsbosbeheer.nl" style="text-decoration:none;" target="_blank">Staatsbosbeheer</a>: ESRI-bestanden van natuurgebieden (Jac Hakkens)</li>
	<li><a href="https://www.natuurmonumenten.nl" style="text-decoration:none;" target="_blank">Vereniging Natuurmonumenten</a>: ESRI-bestanden van natuurgebieden (Rombout de Wijs)</li>
	<li><a href="http://www.pwn.nl" style="text-decoration:none;" target="_blank">PWN</a>: ESRI-bestanden van natuurgebieden (Hubert Kivit)</li>
	<li><a href="http://www.landschapnoordholland.nl" style="text-decoration:none;" target="_blank">Landschap Noord-Holland</a>: ESRI-bestanden van natuurgebieden (Ron van \'t Veer)</li>
	<li><a href="http://www.cbs.nl/nl-NL/menu/home/default.htm" target="_blank">Centraal Bureau voor de Statistiek</a>: ESRI-bestanden van gemeenten</li>
	<li><a href="http://gadm.org/" target="_blank">Global Administrative Areas</a>: ESRI-bestanden van administratieve gebieden</li>
</ul>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_summary' => '',
      ),
    ),
  ),
  'date' => '2017-05-01 13:32:41 +0000',
  'user_uuid' => '3f7b751f-de9b-4b15-b939-437e11ff7ae7',
);
  $nodes[] = array(
  'title' => 'Colofon',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'ds_switch' => '',
  'type' => 'naturalis_service_menu_page',
  'language' => 'nl',
  'created' => 1418384361,
  'tnid' => 4,
  'translate' => 0,
  'uuid' => '9a48e336-4f8f-40f2-954c-8a5e89ba8e66',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<h2>Gebruiksvoorwaarden</h2>

<p>Tenzij anders aangegeven is op de gegevens op deze site de <a href="http://creativecommons.nl/uitleg/" style="text-decoration:none;"><u>Creative Commons</u></a> Zero verklaring van toepassing. Dit betekent dat iedere vorm van (her)gebruik van de inhoud is toegestaan, met uitzondering van content (zoals fotomateriaal of documenten) waarvan auteursrecht expliciet wordt vermeld.</p>

<h2>Ontwerp en technische realisatie</h2>

<p>Naturalis Biodiversity Center</p>

<h2>Databronnen</h2>

<ul>
	<li>Naturalis Biodiversity Center (botanische en zoölogische specimen, soortinformatie)</li>
	<li>Species 2000 &amp; ITIS Catalogue of Life: Annual Checklist 2014</li>
	<li>Natura 2000: ESRI-bestanden van gemeenten (Annemiek Adams)</li>
	<li>Staatsbosbeheer: ESRI-bestanden van natuurgebieden (Jac Hakkens)</li>
	<li>Vereniging Natuurmonumenten: ESRI-bestanden van natuurgebieden (Rombout de Wijs)</li>
</ul>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_summary' => '',
      ),
    ),
  ),
  'date' => '2014-12-12 11:39:21 +0000',
  'user_uuid' => '3f7b751f-de9b-4b15-b939-437e11ff7ae7',
);
  $nodes[] = array(
  'title' => 'Contact',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'ds_switch' => '',
  'type' => 'naturalis_service_menu_page',
  'language' => 'en',
  'created' => 1413984173,
  'tnid' => 6,
  'translate' => 0,
  'uuid' => 'a2f56bf1-1289-45f2-96a5-c25a057d6679',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<h2>Questions and feedback for BioPortal</h2>

<table border="0" style="width:100%">
	<tbody>
		<tr>
			<td style="width:50%">E-mail</td>
			<td><a href="mailto:bioportal@naturalis.nl">bioportal@naturalis.nl</a></td>
		</tr>
	</tbody>
</table>

<h2>Naturalis Biodiversity Center</h2>

<table border="0" style="width:100%">
	<tbody>
		<tr>
			<td style="width:50%">Visiting address</td>
			<td>Darwinweg 2, 2333 CR Leiden</td>
		</tr>
		<tr>
			<td>Postal address</td>
			<td>Postbus 9517, 2300 RA Leiden</td>
		</tr>
		<tr>
			<td>Telephone number</td>
			<td>+ 31-(0)71 568 7600</td>
		</tr>
		<tr>
			<td>Fax</td>
			<td>+ 31-(0)71 568 7666</td>
		</tr>
		<tr>
			<td>E-mail</td>
			<td><a href="mailto:contact@naturalis.nl">contact@naturalis.nl</a></td>
		</tr>
		<tr>
			<td>Office address</td>
			<td>Darwinweg 2, 2333 CR Leiden</td>
		</tr>
	</tbody>
</table>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_summary' => '',
      ),
    ),
  ),
  'date' => '2014-10-22 13:22:53 +0000',
  'user_uuid' => '3f7b751f-de9b-4b15-b939-437e11ff7ae7',
);
  $nodes[] = array(
  'title' => 'API',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'ds_switch' => '',
  'type' => 'naturalis_page',
  'language' => 'nl',
  'created' => 1493645348,
  'tnid' => 411615,
  'translate' => 0,
  'uuid' => 'e96f0452-3460-4202-964f-9451ae5a7aa9',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<h2>Netherlands Biodiversity API is een biodiversiteitsdataservice</h2>

<p>De Netherlands Biodiversity API is een moderne dataservice voor wetenschappers, applicatieontwikkelaars, nationale en regionale overheidsinstanties, en andere geïnteresseerden in biodiversiteit en biodiversiteitsgegevens. Deze dienst start met het beschikbaar stellen van biodiversiteitsgegevens door het&nbsp;<a href="http://www.naturalis.nl" target="_blank">Naturalis Biodiversity Center</a>. &nbsp;Door haar zeer omvangrijke catalogi open te stellen komen diverse soorten historische en actuele data beschikbaar, namelijk specimen-, multimedia- en taxongegevens.</p>

<h2>Netherlands Biodiversity API biedt mogelijkheden</h2>

<p>De vrijgegeven gegevens zijn uitstekend geschikt voor gebruik door wetenschappers, werkzaam in het taxonomisch en thematisch biodiversiteitsonderzoek. Gedetailleerde inventarisaties van verschillende aard en een brede variëteit aan (historische) data-analyses behoren tot de gebruiksmogelijkheden. Voor overheden kunnen de gegevens een belangrijke bron van informatie vormen bij het ontwikkelen van nieuw natuur(bescherming)beleid, en, het evalueren en monitoren van staand beleid op dit terrein. Applicatieontwikkelaars tenslotte kunnen voor specifieke doelgroepen planten, paddenstoelen, dieren, fossielen, mineralen en gesteenten tot leven laten komen in interactieve applicaties.</p>

<h2>Netherlands Biodiversity API begint met het ontsluiten van de omvangrijke Naturalis Collectie</h2>

<p>De collectie van Naturalis behoort tot de grootste van de wereld. Behalve de hoeveelheid, is de kwaliteit van de objecten hoog en vertegenwoordigen ze een onschatbare wetenschappelijke waarde. Gefinancierd vanuit de FES gelden heeft Naturalis de afgelopen jaren een uniek digitaliseringsproject uitgevoerd, waarmee alle 37 miljoen objecten op 1 juli 2015 digitaal in kaart zijn gebracht, &nbsp;waarvan 7 miljoen objecten op een hoog detailniveau. Dit alles maakt dat de Netherlands Biodiversity API reeds bij de start een omvangrijk karakter heeft met een waardevolle mate van diepgang.</p>

<h2>Netherlands Biodiversity API is vrij toegankelijk</h2>

<p>Tenzij anders aangegeven zet Naturalis al haar data in het open domein onder&nbsp;<a href="http://creativecommons.nl/publiek-domein/" target="_blank">CC0-licentie</a>, dus vrij voor een ieder om te gebruiken. Een gebruiker heeft dus geen autorisatie nodig om toegang te krijgen tot de biodiversiteitsgegevens.&nbsp;Dit betekent dat iedere vorm van (her)gebruik van de inhoud is toegestaan, met uitzondering van content (zoals fotomateriaal of documenten) waarvan auteursrecht expliciet wordt vermeld.</p>

<h2>Netherlands Biodiversity API en compatibiliteit</h2>

<p>Naturalis streeft naar compatibiliteit bij het onderhoud van deze API met eerdere versies. Wanneer het noodzakelijk is om functionaliteit toe te voegen waardoor deze compatibiliteit niet meer kan worden gegarandeerd, dan zal de actieve versie nog zes maanden onderhouden worden, en zal de nieuwe functionaliteit alleen in de hogere versie beschikbaar zijn. In het geval van veiligheidsproblemen of onjuist gebruik behoudt Naturalis zich het recht voor om hiervan af te wijken.</p>

<h2>Meer over Netherlands Biodiversity API</h2>

<p>Informatie of vragen over de Netherlands Biodiversity API</p>

<p>Op <a href="http://docs.biodiversitydata.nl/en/latest/" target="_blank">Github</a> vindt u meer functionele en technische informatie over de API.</p>

<p>Voor vragen, verzoeken en opmerkingen kunt u mailen met: <a href="mailto:nba@naturalis.nl">nba@naturalis.nl</a></p>

<p>&nbsp;</p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_summary' => '',
      ),
    ),
  ),
  'field_file' => array(),
  'path' => array(
    'pathauto' => 1,
  ),
  'pathauto_perform_alias' => FALSE,
  'date' => '2017-05-01 13:29:08 +0000',
  'user_uuid' => '3f7b751f-de9b-4b15-b939-437e11ff7ae7',
);
  $nodes[] = array(
  'title' => 'Help',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'ds_switch' => '',
  'type' => 'naturalis_help',
  'language' => 'en',
  'created' => 1418640288,
  'tnid' => 2,
  'translate' => 0,
  'uuid' => 'f5db4539-d3d6-4008-8725-ad5156f4be66',
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<p>On this site, you can search for multimedia, specimens (collection specimens) and taxa (species descriptions of animals, plants, fungi), fossils, minerals and rocks.</p>

<p>The information will be supplied from the catalogues of <a href="http://www.naturalis.nl/en/" style="text-decoration:none;" target="_blank">Naturalis Biodiversity Center</a> in Leiden, from the <a href="http://www.nederlandsesoorten.nl/" style="text-decoration:none;" target="_blank">Nederlands Soortenregister</a> and the <a href="http://www.catalogueoflife.org/" style="text-decoration:none;" target="_blank">Catalogue of Life</a>.</p>

<p>On practically every specimen-page a PURL (Persistent Uniform Resource Locator) is present. You can cite the object described here by using this PURL. Naturalis will try to assure the permanent character of this PURL.</p>

<p>The BioPortal offers four possibilities for browsing this data:</p>

<ul>
	<li><a href="#simple-search"><em>simple search</em></a></li>
	<li><a href="#advanced-search"><em>advanced search</em></a></li>
	<li><em><a href="#geo-search">geographic search</a></em></li>
	<li><em><a name="simple-search"></a><a href="#explore-highlights">explore highlights</a></em></li>
</ul>

<h2><strong>Searching</strong></h2>

<p><br />
<strong>Simple Search</strong></p>

<p>Bioportal works in the same way as other well-known search engines: it uses your search terms to browse our sources. Within its search operations, it will examine all the fields specified in the advanced search (such as popular name, scientific name or discovery location) and will even browse fields not accessible via the advanced search.</p>

<p>Example: you can search for either [ brown rat ] or [ rattus norvegicus ].</p>

<p>If you type more than one search term, we will display all the results in which one, some or all of the terms occur, but we will head the list with results with the best match.</p>

<p>When you make a simple search the search term will be analysed and if there are more terms the search is divided into various parts. All these parts lead to potential search results and are combined with an OR, which can lead to very big search result sets.</p>

<p><a name="advanced-search"></a>It is not possible to use brackets or so-called wildcards. All foreign characters will be ignored in the query. To combine search terms, use the <a href="#advanced-search">Advanced Search</a> option.</p>

<p>&nbsp;</p>

<h3><strong>Advanced Search</strong></h3>

<p>By clicking on the triangle symbol in the entry field, you will leave the <em>simple search </em>application, and start an <em>advanced search</em>. This means that you will limit your results to the category in which you are searching (multimedia, specimen or taxon) and to the specific fields in which you are searching.</p>

<p>If you enter search terms for more than one category, the result for each category will be shown.</p>

<p>If you enter more than one search field within a single category, initially, those results will be shown that include one or more of these terms.</p>

<p>If you opt to use ‘And’ for ‘Combine search terms’, the search engine will display results that contain all terms; in other words you will reduce the number of results.</p>

<p><a name="geo-search"></a>Within the categories specimens and multimedia, you also have the option to restrict your search to a specific collection by selecting its name in the Collection name field. You can also limit your query for the categories Collection specimens, Taxa and Multimedia by selecting a specific Source (e.g. Botany or Zoology and Geology catalogues).</p>

<p>&nbsp;</p>

<h3><strong>Geographic Search</strong></h3>

<p>You can use a geographic search to rapidly limit the number of search results to a particular area. The area can be selected from a list of areas on the right-hand side of the map, or drawn onto the map.</p>

<p>The results will always be limited to collection specimens and multimedia. Within this search type, only those results for which the geographical coordinates of the discovery location are stored in the source systems will be displayed.</p>

<p><em><a id="explore-highlights" name="explore-highlights"></a></em>We make use of a range of different <a href="http://bioportal.naturalis.nl/colophon#sources?language=en" target="_blank">sources</a>. This means that in some cases, areas may be listed more than once. These areas will often differ in terms of degree of detail of the boundaries.</p>

<p>&nbsp;</p>

<h3><strong>Explore Highlights</strong></h3>

<p>A simple and rapid search method is ‘Explore Highlights’. This search will result in a reproduction of all specimens that belong to one of the Special Collections at Naturalis. The results will be displayed immediately.</p>

<h2><strong>Search results</strong></h2>

<p>The aim of BioPortal is to deliver the results you are looking for quickly, and with that in mind, the system will use <em>name resolution</em> and <em>ranking</em>.</p>

<h3><strong>Name resolution</strong></h3>

<p>The BioPortal will attempt to <em>match</em> your search term to a scientific name. This will be achieved by browsing through various fields in the <a href="http://www.nederlandsesoorten.nl/" target="_blank">Nederlands Soortenregister</a> and the <a href="http://www.catalogueoflife.org/" target="_blank">Catalogue of Life</a>.</p>

<p>1. &nbsp;&nbsp;&nbsp;Scientific name<br />
○ &nbsp;&nbsp;&nbsp;&nbsp;For example: <em>“Rattus norvegicus”</em><br />
2. &nbsp;&nbsp;&nbsp;A list of popular names in various languages<br />
○ &nbsp;&nbsp;&nbsp;&nbsp;One example is ‘Bruine Rat’ (Dutch) or “Brown Rat ” (English)<br />
3. &nbsp;&nbsp;&nbsp;Higher orders<br />
○ &nbsp;&nbsp;&nbsp;&nbsp;For example “Rodentia” for the biological order rodents</p>

<p>This scientific name is then used to browse through multimedia and specimens. This may mean that your original query will not necessarily be literally reproduced in certain results.</p>

<h3><strong>Ranking</strong></h3>

<p>The search results will be ranked according to</p>

<p>1. &nbsp;&nbsp;&nbsp;Full <em>match</em> for the scientific name<br />
2. &nbsp;&nbsp;&nbsp;Full <em>match</em> for the species name<br />
3. &nbsp;&nbsp;&nbsp;Full <em>match</em> for the genus name<br />
4. &nbsp;&nbsp;&nbsp;Partial <em>match</em> for the scientific name<br />
5. &nbsp;&nbsp;&nbsp;Full <em>match</em> for any other field<br />
6. &nbsp;&nbsp;&nbsp;Partial <em>match</em> for any other field<br />
7. &nbsp; &nbsp;The number of times a matched is found/&nbsp;The importance of a field</p>

<p><strong>Categories</strong><br />
<br />
The search results are divided into four categories:</p>

<p>1. &nbsp;&nbsp;&nbsp;Multimedia: pictures, sound or moving images from all data<br />
2. &nbsp;&nbsp;&nbsp;Taxa (species description)<br />
3. &nbsp;&nbsp;&nbsp;Specimens with the search term in the species name.&nbsp;Generates results if the search term occurs in the &nbsp;taxonomical information of the specimen<br />
4. &nbsp;&nbsp;&nbsp;Specimens with the search term in another field.&nbsp;Generates results if the search term occurs in (for example) collection information, geographical information or information relating to time and dates.&nbsp;‘Rat’ also generates results for ‘Rat Island in Plymouth, UK.</p>

<p>Specimens are references to and descriptions of objects stored in the Naturalis collection (and sometimes other collections). These descriptions can contain many different fields.</p>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_summary' => '',
      ),
    ),
  ),
  'path' => array(
    'pathauto' => 0,
  ),
  'pathauto_perform_alias' => FALSE,
  'date' => '2014-12-15 10:44:48 +0000',
  'user_uuid' => '3f7b751f-de9b-4b15-b939-437e11ff7ae7',
);
  return $nodes;
}
