<?php
/**
 * @file
 * searchtax.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function searchtax_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'taxonomy_term-search-field_ndadatatype'
  $field_instances['taxonomy_term-search-field_ndadatatype'] = array(
    'bundle' => 'search',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Datatype',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 1,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_ndadatatype',
    'label' => 'Datatype',
    'required' => FALSE,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 4,
    ),
  );

  // Exported field_instance: 'taxonomy_term-search-field_ndageorelevance'
  $field_instances['taxonomy_term-search-field_ndageorelevance'] = array(
    'bundle' => 'search',
    'default_value' => array(
      0 => array(
        'value' => 1,
      ),
    ),
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'list',
        'settings' => array(),
        'type' => 'list_default',
        'weight' => 3,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_ndageorelevance',
    'label' => 'Geo relevance',
    'required' => 0,
    'settings' => array(
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'options',
      'settings' => array(
        'display_label' => 0,
      ),
      'type' => 'options_onoff',
      'weight' => 6,
    ),
  );

  // Exported field_instance: 'taxonomy_term-search-field_ndasystem'
  $field_instances['taxonomy_term-search-field_ndasystem'] = array(
    'bundle' => 'search',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Description',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_ndasystem',
    'label' => 'System',
    'required' => TRUE,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 3,
    ),
  );

  // Exported field_instance: 'taxonomy_term-search-field_ndavalues'
  $field_instances['taxonomy_term-search-field_ndavalues'] = array(
    'bundle' => 'search',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 4,
      ),
    ),
    'entity_type' => 'taxonomy_term',
    'field_name' => 'field_ndavalues',
    'label' => 'Values',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 7,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Datatype');
  t('Description');
  t('Geo relevance');
  t('System');
  t('Values');

  return $field_instances;
}
