<?php

/**
 * @file
 * Naturalis bioportal module used to integrate Drupal with the Naturalis Data API formally
 * known as the NDA.
 * @version 0.1
 * @author Naturalis
 * @package Bioportal
 */
 
$phaseOrStage = 'adult|egg|embryo|immature|juvenile|larva|nymph|subadult';
$sex = 'female|hermaphrodite|male|mixed';
$typeStatus = 'allotype|epitype|holotype|isoepitype|isolectotype|isoneotype|isosyntype|isotype|lectotype|neotype|paralectotype|paratype|syntype|topotype';
$kingdom = 'Animalia|Archaea|Bacteria|Chromista|Fungi|Plantae|Protozoa|Viruses';
$taxonomicStatus = 'basionym|homonym|synonym|valid name';

/**
 * Default value for the NDA. Can be overridden in the module config page.
 * <siteroot>/admin/config/naturalis
 */
define('NDABIO_NDA', 'http://nda.naturalis.nl');
/**
 * Default value for the NDA GET service. Can be overridden in the module config page.
 * <siteroot>/admin/config/naturalis
 */
define('NDABIO_JSON', 'http://10.42.1.121:8080/nl.naturalis.nda.service.rest/api/specimen/search/');
/**
 * Default value for the NDA POST service. Can be overridden in the module config page.
 * <siteroot>/admin/config/naturalis
 */
define('NDABIO_JSONPOST', 'http://10.42.1.121:8080/nl.naturalis.nda.service.rest/api/specimen/search/');
/**
 * Default value for the GMAP key. Can be overridden in the module config page.
 * <siteroot>/admin/config/naturalis
 */
define('NDABIO_GMAPKEY', 'AIzaSyCv168azSiPAf0wjVe36gNqdANDqEXkpvQ');

/**
 * Advanced search used a drupal taxonomy. This is the systemname of the taxonomy used for
 * building the advances search form.
 * <siteroot>/admin/config/naturalis
 */
define('NDABIO_SEARCHTAXONOMY', 'search');

/**
 * DEFINE CUSTOM PAGES
 * Module administration and all custom pages. Each page includes a callback where the
 * page functionality is defined.
 * @package custompages
 */

/**
 * Implements hook_menu().
 */
function ndabio_menu() {
  //Configuration page
  $items['admin/config/naturalis'] = array(
    'title' => 'Naturalis config',
    'description' => 'Configuration for Naturalis module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ndabio_config_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['search/geosearch'] = array(
    'page callback' => 'ndabio_displayform',
    'page arguments' => array('geo'),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  $items['geographic-search'] = array(
    'page callback' => 'ndabio_displayform',
    'page arguments' => array('geo'),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['naturalis/ndadetail'] = array(
    'title' => 'Details',
    'page callback' => 'ndabio_ndadetail_callback',
    'page arguments' => array(2, 3),
    'access arguments' => array('access content'),
  );

  //Currently used as front page
  $items['search/advancednda'] = array(
    'page callback' => 'ndabio_displayform',
    'access arguments' => array('access content'),
    'title' => t('Advanced Naturalis Data Search'),
    'type' => MENU_LOCAL_TASK,
  );
  $items['search/ndapass'] = array(
    'page callback' => 'ndabio_pass',
    'access arguments' => array('access content'),
  );

  //Page used by javascript to retrieve geo coordinates based on a nid
  $items['naturalis/ajax'] = array(
   'page callback' => 'ndabio_ajax_callback',
   'access arguments' => array('access content'),
   'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
* Output a json formatted detail page with geocoordinates based on the nid passed in the url.
*/
function ndabio_ajax_callback() {
  $geonode = (int)$_GET["nid"];

  $sql = "SELECT n.nid, n.title, g.field_geojson_value, s.field_source_value, t.field_type_value FROM {node} n , {field_data_field_geojson} g, {field_data_field_source} s, {field_data_field_type} t WHERE n.nid = $geonode AND n.nid = t.entity_id AND n.nid = g.entity_id AND n.nid = t.entity_id";

  $row = db_query($sql)->fetchObject();

  if($row) {
    echo '{"nid":' . $geonode . ',"locality":' . json_encode($row->title) . ',"source":' . json_encode($row->field_source_value) . ',"geometry":' . $row->field_geojson_value . '}';
  }
  die();
}


/**
 * Output detail page.
 */
function ndabio_ndadetail_callback($myid = '', $myaction = NULL) {
  return "<h2>" . t("My ID") . "</h2><pre>" . $myid . " " . $myaction . "</pre>";
}

/**
 *
 */
function ndabio_config_form($form, &$form_state) {
  $form['ndabio_config'] = array(
    '#type' => 'fieldset',
    '#title' => t('Naturalis Data API config')
  );
  $form['ndabio_config']['ndabio_config_nda'] = array(
    '#type' => 'textfield',
    '#title' => t('Naturalis Data API URL'),
    '#default_value' => variable_get('ndabio_config_nda', NDABIO_NDA),
    '#size' => 140,
    '#maxlength' => 200,
    '#description' => t('The URL of the Naturalis Data API, used for sending queries.') . '<br />' .
      t('Default') . ': ' . NDABIO_NDA,
    '#required' => TRUE,
  );
  $form['ndabio_config']['ndabio_config_json'] = array(
    '#type' => 'textfield',
    '#title' => t('NDA Get URL'),
    '#default_value' => variable_get('ndabio_config_json', NDABIO_JSON),
    '#size' => 140,
    '#maxlength' => 200,
    '#description' => t('The URL used for sending GET requests. Expects a JSON reply.') . '<br />' .
      t('Default') . ': ' . NDABIO_JSON,
    '#required' => TRUE,
  );
  $form['ndabio_config']['ndabio_config_jsonpost'] = array(
    '#type' => 'textfield',
    '#title' => t('NDA Post URL'),
    '#default_value' => variable_get('ndabio_config_jsonpost', NDABIO_JSONPOST),
    '#size' => 140,
    '#maxlength' => 200,
    '#description' => t('The URL used for sending POST requests. Expects a JSON reply.') . '<br />' .
      t('Default') . ': ' . NDABIO_JSONPOST,
    '#required' => TRUE,
  );
  $form['ndabio_gmap'] = array(
    '#type' => 'fieldset',
    '#title' => t('Naturalis Geosearch config')
  );
  $form['ndabio_gmap']['ndabio_config_gmapkey'] = array(
    '#type' => 'textfield',
    '#title' => t('Google maps key'),
    '#default_value' => variable_get('ndabio_config_gmapkey', NDABIO_GMAPKEY),
    '#size' => 140,
    '#maxlength' => 200,
    '#description' => t('The key used by Google maps for a geographic search.') . '<br />' .
      t('Default') . ': ' . NDABIO_GMAPKEY,
    '#required' => TRUE,
  );

  return system_settings_form($form);
}

/**
 *
 */
function ndabio_displayform($arg1 = "") {
  if ($arg1 === "geo") variable_set("geosearch", "1");
  else variable_set("geosearch", "0");
  $form = drupal_get_form('ndabio_advanced_taxonomysearch');
  return (drupal_render($form));
}

/**
 *
 */
function _wrap_inner_grid_cols( &$form_element, $n = 6 ){
  if (!isset($form_element['#prefix']) ) $form_element['#prefix'] = '';
  if (!isset($form_element['#suffix']) ) $form_element['#prefix'] = '';
  $form_element['#prefix'] = $form_element['#suffix'] . "<div class='small-$n columns'>";
  $form_element['#suffix'] = "</div>" . $form_element['#suffix'];
}

/**
 * Implements hook_theme().
 */
function ndabio_theme($existing, $type, $theme, $path) {
  //Provide a theme function for the 'omnisearch' field
  $data['ndabio_omnisearch'] = array(
    'render element' => 'element',
  );
  return $data;
}

/**
 * Check if a string is JOSN.
 * @param string
 * @return boolean
 */
function isJson($string) {
  json_decode($string);
  return (json_last_error() == JSON_ERROR_NONE);
}

/**
 * GEO data is passed to this page as an node id. The node contains all geo data, and should be posted to the NDA
 */
function ndabio_pass() {
  $path = drupal_get_path('module', 'ndabio');
  $mynode = node_load($_GET['geometry']);
  $mycontent = "Selected map: " . $mynode->title . "<br />";
  $mycontent .= "Source: " . $mynode->field_source['und'][0]['value'] . "<br />";
  $mycontent .= "Type: " . $mynode->field_type['und'][0]['value'] . "<br />";
  $mycontent .= "JSON: " . substr($mynode->field_geojson['und'][0]['value'], 0, 100) . "... <br />";
  $keys = "geo=" . urlencode($mynode->field_geojson['und'][0]['value']);
  return $mycontent . ndabio_postjson($keys = '');
}

/**
 * Post a query to the NDA.
 */
function ndabio_postjson($keys = '') {
  $service_url = variable_get('ndabio_config_jsonpost', NDABIO_JSONPOST);
  drupal_set_message("POST:" . $service_url);

  $curl = curl_init($service_url);
  curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
  curl_setopt($curl, CURLOPT_POST, 1);
  curl_setopt($curl, CURLOPT_POSTFIELDS, $keys);
  curl_setopt($curl, CURLOPT_HTTPHEADER, array("Expect:"));
  $curl_response = curl_exec($curl);
  $http_status = curl_getinfo($curl, CURLINFO_HTTP_CODE);
  curl_close($curl);
  if ($http_status >= 400) {
    drupal_set_message("Curl returned error: " .  $http_status);
    return " ";
  }
  if (!isJson($curl_response)) {
    drupal_set_message("Curl did not return json: " .  $curl_response);
    return " ";
  }
  return $curl_response;
}



/**
 * Get a JSON string.
 */
function ndabio_getjson($url = '') {
  $service_url = $url;
  drupal_set_message("GET:" . $service_url);

  $curl = curl_init($service_url);
  curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
  curl_setopt($curl, CURLOPT_HTTPHEADER, array("Expect:"));
  $curl_response = curl_exec($curl);
  $http_status = curl_getinfo($curl, CURLINFO_HTTP_CODE);
  curl_close($curl);
  if ($http_status >= 400) {
    drupal_set_message("Curl returned error: " .  $http_status);
    return " ";
  }
  if (!isJson($curl_response)) {
    drupal_set_message("Curl did not return json: " .  $curl_response);
    return " ";
  }
  return $curl_response;
}

/**
 * DEFINE CUSTOM BLOCKS
 */

/**
 * Implements hook_block_info().
 */
function ndabio_block_info() {
 $blocks['ndabio_copyright_block'] = array(
  'info' => t('Naturalis: Copyright'),
  '#attached' => array(
      'css' => array(
        drupal_get_path('module', 'naturalis') . '/css/naturalis.css',
      ),
      'js' => array(
      ),
    ),
  );
 $blocks['ndabio_search_block'] = array(
  'info' => t('Naturalis: Search'),
  '#attached' => array(
      'css' => array(
        drupal_get_path('module', 'naturalis') . '/css/naturalis.css',
      ),
      'js' => array(
      ),
    ),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function ndabio_block_view($delta = '') {
  global $base_root, $base_path;
  $block = array();

  switch ($delta) {
    case 'ndabio_copyright_block':
      $block['content'] = t('Copyright') . ' ' . date("Y") . ' ' .
        '<a href="' . variable_get('ndabio_copyright_url', $base_root . $base_path) . '">' .
        variable_get('ndabio_copyright_label', 'Naturalis') . '</a>';
      break;
  }

  return $block;
}

/**
 * Implements hook_block_configure().
 */
function ndabio_block_configure($delta = '') {
  global $base_root, $base_path;
  $form = array();
  if ($delta == 'ndabio_copyright_block') {
    $form['ndabio_copyright_url'] = array(
      '#type' => 'textfield',
      '#title' => t('Naturalis copyright URL'),
      '#size' => 80,
      '#description' => t('The URL where the copyright message is pointing to.' . '<br />' .
        t('Default') . ': ' . $base_root . $base_path),
      '#default_value' => variable_get('ndabio_copyright_url', $base_root . $base_path),
    );
    $form['ndabio_copyright_label'] = array(
      '#type' => 'textfield',
      '#title' => t('Naturalis copyright label'),
      '#size' => 80,
      '#description' => t('The label of the copyright owner.' . '<br />' .
        t('Default') . ': ' . t('Naturalis')),
      '#default_value' => variable_get('ndabio_copyright_label', 'Naturalis'),
    );
  }
  return $form;
}

/**
 * Implements hook_block_save().
 */
function ndabio_block_save($delta = '', $edit = array()) {
  if ($delta == 'ndabio_copyright_block') {
    variable_set('ndabio_copyright_url', $edit['ndabio_copyright_url']);
    variable_set('ndabio_copyright_label', $edit['ndabio_copyright_label']);
  }
}

/**
 * DEFINE CRON JOB
 */

/**
 * Implements hook_cron().
 */
function ndabio_cron() {
  drupal_set_message("Naturalis: Run cron");
}

/**
 * DEFINE CUSTOM (BASIC) SEARCH
 */


/**
 * Implements hook_search_page().
 */
function ndabio_search_page($results) {
  //drupal_set_message("Naturalis: ndabio_search_page");

  $output['prefix']['#markup'] = '<h2>Search results ' . '</h2>' ;
  $output['prefix']['#markup'] .= '<ol class="search-results">';

  if(!empty($results)) {
    foreach ($results as $entry) {
      $output[] = array(
        '#theme' => 'search_result',
        '#result' => $entry,
        '#module' => 'naturalis',
      );
    }
  }
  $output['suffix']['#markup'] = '</ol>' . theme('pager');

  return $output;
}

/**
 * 'search' TAXONOMY TO ADVANCED SEARCH FORM
 */
function ndabio_advanced_taxonomysearch() {
  $geosearch = 0;
  if(variable_get('geosearch') == '1') {
    global $base_root, $base_path;
    $geosearch = 1;
    $path = drupal_get_path('module', 'ndabio');
    drupal_add_css($path . "/css/ndabio_style.css");
    drupal_add_js($path . "/js/map.js", array('weight' => 1));
    drupal_add_js("https://maps.googleapis.com/maps/api/js?key=" . variable_get('ndabio_config_gmapkey', NDABIO_GMAPKEY) . "&libraries=drawing");
    drupal_add_js("jQuery(document).ready(function() { google.maps.event.addDomListener(window, 'load', initialize); });", 'inline');
    drupal_add_js("var str_base_path = '$base_path' ",'inline');
  }
  $searchtype = array(0 => t('And'), 1 => t('Or'));

  $machine_name = "search";
  $v = taxonomy_vocabulary_machine_name_load($machine_name);
  $terms = taxonomy_get_tree($v->vid, 0, 1, TRUE);

  $form = array();
  foreach($terms as $item) {
    $name = $item->name;
    $label = $item->description;
    $sysname = $item->name;
    if (!empty($item->field_ndasystem)) $sysname = $item->field_ndasystem['und'][0]['safe_value'];

    $children = taxonomy_get_children($item->tid, $item->vid);
    if ($children) {
      $form[$sysname] = array(
        '#type' => 'fieldset',
        '#id' => "edit-$sysname",
        '#attributes' => array( 'form_id' => 'ndabio_advanced_taxonomysearch')
        //'#title' => $label,
      );

      foreach ($children as $child) {
        $childlabel = $child->description;
        $childsysname = $child->name;
        $fieldsetPrefix = strtolower(substr(end(explode(" ", $childsysname)), 0, 1));
        $childgeorelevance = 0;
        if (!empty($child->field_ndageorelevance)) $childgeorelevance = $child->field_ndageorelevance['und'][0]['value'];
        if (!empty($child->field_ndasystem)) $childsysname = $child->field_ndasystem['und'][0]['safe_value'];
        $subchildren = taxonomy_get_children($child->tid, $child->vid);
        if ($subchildren && ((!$geosearch) || ($geosearch && $childgeorelevance))) {
          $form[$sysname][$childsysname] = array(
            '#type' => 'fieldset',
            '#title' => $childlabel,
            $fieldsetPrefix . '_andOr' => array(
              '#type' => 'radios',
              '#title' => t('Combine searchterms'),
              '#default_value' => 0,
              '#options' => $searchtype,
              '#inline' => TRUE
            ),
          );
          foreach ($subchildren as $subchild) {
            $subchildlabel = $subchild->description;
	    $subchildsysname = $subchild->name;
	    $subchildvalues = "";
            if (!empty($subchild->field_ndasystem)) $subchildsysname = $subchild->field_ndasystem['und'][0]['safe_value'];
	    if (!empty($subchild->field_ndavalues)) $subchildvalues = $subchild->field_ndavalues['und'][0]['safe_value'];

            //Special category, hide or pulldown fields
            if (($subchild->name == "--more--") || ($subchild->name == "--hide--")) {
              //--more-- will be grouped in a new fieldset
              //--hide-- will be ignored (not added to the form)

              $category = taxonomy_get_children($subchild->tid, $subchild->vid);
              if ($category && ($subchild->name == "--more--")) {
                $form[$sysname][$childsysname][$subchildsysname][$subchild->name] = array(
                  '#type'            => 'fieldset',
                  '#title'           => t("More"),
                  '#collapsible'     => TRUE,
                  '#collapsed'       => TRUE,
                  '#attributes'    =>  array( 'collapsed' => "true", 'collapsible' => 'true', 'class' => array("collapsible","collapsed", "form-wrapper") )
                );

                //put all children in group
                foreach ($category as $catitem) {
				$lvalues = "";
				  if (!empty($catitem->field_ndavalues)) $lvalues = $catitem->field_ndavalues['und'][0]['safe_value'];
				  if ($lvalues != "") {
 			    unset($optionarray);
				$optionarray[""] = ""; //First entry is an empty string 
                foreach(explode("|", $lvalues) as $optionitem ) {
                  $optionarray[$optionitem] = $optionitem;
                }
                 $form[$sysname][$childsysname][$subchildsysname][$subchild->name][$catitem->name] = array(
                    '#type'          => 'select',
                    '#title'         => $catitem->description,
                    '#options'       =>  $optionarray,
                    '#default_value' => '',
                    '#required'      =>  FALSE,
                    '#inline'        =>  TRUE,
                  );
				  
				  }
				  else {
                  $form[$sysname][$childsysname][$subchildsysname][$subchild->name][$catitem->name] = array(
                    '#type'          => 'textfield',
                    '#title'         => $catitem->description,
                    '#default_value' => '',
                    '#required'      =>  FALSE,
                    '#inline'        =>  TRUE,
                  );
				  }
                }
              }
            } else {
              //Default search fields
              if ($subchildvalues != "") {
			    unset($optionarray);
				$optionarray[""] = ""; //First entry is an empty string 
                foreach(explode("|", $subchildvalues) as $optionitem ) {
                  $optionarray[$optionitem] = $optionitem;
                }
                $form[$sysname][$childsysname][$subchildsysname] = array(
                  '#type'          =>  'select',
                  '#title'         =>  $subchildlabel,
                  '#options'       =>  $optionarray,
                  '#inline'        =>  TRUE,
                  '#attributes'    =>  array( 'data-clear' => "", 'name' => $subchildsysname )
                );
                $subchildvalues = "";
              }
              else {
                $form[$sysname][$childsysname][$subchildsysname] = array(
                  '#type'          => 'textfield',
                  '#title'         => $subchildlabel,
                  '#default_value' => '',
                  '#required'      =>  FALSE,
                  '#inline'        =>  TRUE,
                  '#attributes'    =>  array( 'data-clear' => "", 'name' => $subchildsysname )
                );
              }
            }
          }
        } else {
          //Default search fields
		  $childvalues = "";
	      if (!empty($child->field_ndavalues)) $childvalues = $child->field_ndavalues['und'][0]['safe_value'];
              if ($childvalues != "") {
			    unset($optionarray);
				$optionarray[""] = ""; //First entry is an empty string 
                foreach(explode("|", $childvalues) as $optionitem ) {
                  $optionarray[$optionitem] = $optionitem;
                }
                $form[$sysname][$childsysname] = array(
                  '#type'          =>  'select',
                  '#title'         =>  $childlabel,
                  '#options'       =>  $optionarray,
                  '#inline'        =>  TRUE,
                  '#attributes'    =>  array( 'data-clear' => "", 'name' => $childsysname )
                );
                $subchildvalues = "";
              }
              else {
          $form[$sysname][$childsysname]['#type'] = array(
            '#type'          => 'textfield',
            '#title'         => $childlabel,
            '#default_value' => '',
            '#required'      =>  FALSE,
            '#inline'        =>  TRUE,
            '#attributes'    =>  array( 'data-clear' => "", 'name' => $childsysname )
          );
		  }
        }
      }
    } else {
      // Omnisearch Box
      $form[$sysname]['omnisearch'] = array(
        '#type' => 'fieldset',
        '#theme' => 'ndabio_omnisearch',
        '#nowrapper' => TRUE,
        '#attributes' => array( 'class' => array('fieldset-omnisearch'))
      );

      $form[$sysname]['omnisearch']['term'] = array(
        '#type' => 'textfield',
        '#title' => t('Keywords'),
        '#default_value' => '',
        '#required' => FALSE,
        '#title_display' => 'invisible',
        '#nowrapper' => TRUE,
        '#id' => "edit-term",
        '#attributes' => array( 'name' => 'term')
       );

      $form[$sysname]['omnisearch']['submit'] = array(
        '#type' => 'submit',
        '#value' => t('Search'),
        '#nowrapper' => TRUE,
        '#attributes' => array( 'class' => array('postfix')),
        '#id' => 'edit-submit-top'
      );
    }
  }
  
  if($geosearch) {
    $links =
       "<div id='search-areas-types' class='small-12 medium-2 columns chained-select chained-select-level-1'>"
      ."  <ul>"
      ."    <li>"
      ."      <a data-rel='ajax' href='areas/country?response_type=embed'>Landen</a>"
      ."    </li>"
      ."    <li>"
      ."      <a data-rel='ajax' href='areas/municipality?response_type=embed'>Gemeentes</a>"
      ."    </li>"
      ."    <li>"
      ."      <a data-rel='ajax' href='areas/nature?response_type=embed'>Natuurgebieden</a>"
      ."    </li>"
      ."  </ul>"
      ."</div>";

    $list =
       "<div id='search-areas-list' class='small-12 medium-3 columns'>"
      ."  <input id='search-areas-filter' placeholder='« filter »' />"
      ."  <div id='search-areas-target'></div>"
      ."</div>";
	  
    $form['gmap'] = array(
      '#type' => 'gmap',
      '#map' => 'gmap',
      '#settings' => array(
        'zoom' => 1,
        'id' => 'gmapx',
        'behavior' => array(
          'geocode_leave_marker' => TRUE,
        ),
      ),
      '#prefix' => '<div id=\'geographical-search\' class=\'small-12 medium-7 columns\'>',
      '#suffix' => '<div id=\'map-canvas\' style=\'height:600px;\'></div></div>'.$links.$list,
    );
  }
  $form[$sysname]['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Search'),
    '#nowrapper' => TRUE,
    '#id' => 'edit-submit-bottom'
  );
  $form['#action'] = url('nba/result');

  return ($form);
}

/**
 *
 */
function ndabio_advanced_taxonomysearch_callback_submit(&$form, &$form_state) {
  $myvalues = array_diff($form_state['values'], array('form_build_id', 'form_token', 'form_id', 'op', 'submit'));
  unset($myvalues['form_build_id']);
  unset($myvalues['form_token']);
  unset($myvalues['form_id']);
  unset($myvalues['op']);
  unset($myvalues['submit']);

  $myurl = variable_get('ndabio_config_json', NDABIO_JSON) . "?";
  //Default search is AND based. Only add the operator if a non-default is chosen
  if ($myvalues['searchtype'] == 1) $myurl .= "operator=OR&";
  unset($myvalues['searchtype']);

  foreach (array_filter($myvalues) as $key => $val) {
    $myurl .= "$key=" . urlencode($val) . "&";
  }
  drupal_deliver_page("<h2>" . t("Results") . "</h2><pre>" . ndabio_getjson(rtrim($myurl, '&')) . "</pre>");
}
