<?php
/**
 * @file
 * bioportal_header_images.features.uuid_node.inc
 */

/**
 * Implements hook_uuid_features_default_content().
 */
function bioportal_header_images_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
  'title' => 'skelet',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 1,
  'sticky' => 0,
  'ds_switch' => '',
  'type' => 'ndabio_header_image',
  'language' => 'en',
  'created' => 1416470988,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '3250b7b0-0cde-4b3d-88f5-931e0bb1f83f',
  'field_ndabio_header_image' => array(),
  'date' => '2014-11-20 08:09:48 +0000',
  'user_uuid' => '3f7b751f-de9b-4b15-b939-437e11ff7ae7',
);
  $nodes[] = array(
  'title' => 'mineraal4',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 1,
  'sticky' => 0,
  'ds_switch' => '',
  'type' => 'ndabio_header_image',
  'language' => 'en',
  'created' => 1416470934,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '626ffc19-1650-4885-8ccc-3f4ff9ea37a8',
  'field_ndabio_header_image' => array(),
  'date' => '2014-11-20 08:08:54 +0000',
  'user_uuid' => '3f7b751f-de9b-4b15-b939-437e11ff7ae7',
);
  $nodes[] = array(
  'title' => 'zilvermeeuw',
  'log' => '',
  'status' => 1,
  'comment' => 0,
  'promote' => 1,
  'sticky' => 0,
  'ds_switch' => '',
  'type' => 'ndabio_header_image',
  'language' => 'en',
  'created' => 1416470910,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '786b2489-998b-4794-87a6-bef7c2d87fb1',
  'field_ndabio_header_image' => array(),
  'date' => '2014-11-20 08:08:30 +0000',
  'user_uuid' => '3f7b751f-de9b-4b15-b939-437e11ff7ae7',
);
  return $nodes;
}
